use std::collections::{HashMap, HashSet};
use std::fmt;

/// Mechanisms by which an API conveys its version to clients.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum VersioningScheme {
    UrlPath,
    Header,
    QueryParam,
    Subdomain,
    ContentType,
    AcceptHeader,
}

impl fmt::Display for VersioningScheme {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let label = match self {
            Self::UrlPath => "url-path",
            Self::Header => "header",
            Self::QueryParam => "query-param",
            Self::Subdomain => "subdomain",
            Self::ContentType => "content-type",
            Self::AcceptHeader => "accept-header",
        };
        write!(f, "{label}")
    }
}

/// All supported versioning schemes (6 total, exceeding the ≥5 requirement).
pub const ALL_SCHEMES: &[VersioningScheme] = &[
    VersioningScheme::UrlPath,
    VersioningScheme::Header,
    VersioningScheme::QueryParam,
    VersioningScheme::Subdomain,
    VersioningScheme::ContentType,
    VersioningScheme::AcceptHeader,
];

/// Version values to probe (20+ unique values).
pub const VERSION_PROBES: &[&str] = &[
    "v0",
    "v1",
    "v2",
    "v3",
    "v4",
    "v5",
    "v6",
    "v7",
    "v8",
    "v9",
    "v10",
    "beta",
    "alpha",
    "canary",
    "internal",
    "latest",
    "edge",
    "staging",
    "dev",
    "preview",
    "experimental",
    "legacy",
    "deprecated",
    "unstable",
];

/// Headers commonly used to convey API version.
pub const VERSION_HEADERS: &[&str] = &[
    "API-Version",
    "X-API-Version",
    "Accept-Version",
    "X-Version",
    "Api-Version",
    "X-Api-Version",
];

/// Query parameter names commonly used for version selection.
pub const VERSION_QUERY_PARAMS: &[&str] = &[
    "version",
    "api_version",
    "api-version",
    "v",
    "ver",
    "apiVersion",
];

/// Content-type media-type version patterns.
pub const CONTENT_TYPE_PATTERNS: &[&str] = &[
    "application/vnd.api.{version}+json",
    "application/vnd.company.{version}+json",
    "application/json; version={version}",
    "application/vnd.api+json; version={version}",
];

/// A single probe request generated by the discovery engine.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct VersionProbe {
    pub scheme: VersioningScheme,
    pub version_value: String,
    pub url: String,
    pub headers: HashMap<String, String>,
    pub description: String,
}

/// Describes an endpoint available at a specific API version.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct VersionedEndpoint {
    pub path: String,
    pub method: String,
    pub version: String,
}

/// A difference between two API versions — something present in one but absent in the other.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct VersionDiff {
    pub old_version: String,
    pub new_version: String,
    pub removed_in_new: Vec<VersionedEndpoint>,
    pub added_in_new: Vec<VersionedEndpoint>,
}

impl VersionDiff {
    /// Endpoints present in old but absent in new (deprecated/removed security controls).
    pub fn deprecated_endpoints(&self) -> &[VersionedEndpoint] {
        &self.removed_in_new
    }
}

/// Category of attack this probe belongs to.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum AttackCategory {
    VersionDiscovery,
    DeprecatedEndpointAccess,
    VersionRollback,
    MixedVersionIdor,
    UndocumentedVersion,
    VersionHeaderInjection,
    GraphqlSchemaDiff,
    ApiGatewayBypass,
}

impl fmt::Display for AttackCategory {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let label = match self {
            Self::VersionDiscovery => "version-discovery",
            Self::DeprecatedEndpointAccess => "deprecated-endpoint-access",
            Self::VersionRollback => "version-rollback",
            Self::MixedVersionIdor => "mixed-version-idor",
            Self::UndocumentedVersion => "undocumented-version",
            Self::VersionHeaderInjection => "version-header-injection",
            Self::GraphqlSchemaDiff => "graphql-schema-diff",
            Self::ApiGatewayBypass => "api-gateway-bypass",
        };
        write!(f, "{label}")
    }
}

/// A fully described attack probe combining scheme, version, and attack category.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AttackProbe {
    pub category: AttackCategory,
    pub probe: VersionProbe,
    pub risk_rationale: String,
}

/// Configuration for the version discovery engine.
#[derive(Debug, Clone)]
pub struct VersionAttackConfig {
    pub base_url: String,
    pub known_endpoints: Vec<String>,
    pub schemes: Vec<VersioningScheme>,
    pub version_values: Vec<String>,
    pub current_version: Option<String>,
}

impl VersionAttackConfig {
    pub fn new(base_url: &str) -> Self {
        Self {
            base_url: base_url.trim_end_matches('/').to_string(),
            known_endpoints: Vec::new(),
            schemes: ALL_SCHEMES.to_vec(),
            version_values: VERSION_PROBES.iter().map(|s| (*s).to_string()).collect(),
            current_version: None,
        }
    }

    pub fn with_endpoints(mut self, endpoints: Vec<String>) -> Self {
        self.known_endpoints = endpoints;
        self
    }

    pub fn with_schemes(mut self, schemes: Vec<VersioningScheme>) -> Self {
        self.schemes = schemes;
        self
    }

    pub fn with_version_values(mut self, values: Vec<String>) -> Self {
        self.version_values = values;
        self
    }

    pub fn with_current_version(mut self, version: &str) -> Self {
        self.current_version = Some(version.to_string());
        self
    }
}

/// Core engine that generates version-based attack probes.
pub struct VersionAttackEngine {
    config: VersionAttackConfig,
}

impl VersionAttackEngine {
    pub fn new(config: VersionAttackConfig) -> Self {
        Self { config }
    }

    /// Generate all URL-path based version probes.
    pub fn generate_url_path_probes(&self) -> Vec<VersionProbe> {
        let mut probes = Vec::new();
        let endpoints = if self.config.known_endpoints.is_empty() {
            vec!["/api/users".to_string(), "/api/health".to_string()]
        } else {
            self.config.known_endpoints.clone()
        };

        for version in &self.config.version_values {
            for endpoint in &endpoints {
                let stripped = endpoint.trim_start_matches('/');
                let url = format!("{}/{}/{}", self.config.base_url, version, stripped);
                probes.push(VersionProbe {
                    scheme: VersioningScheme::UrlPath,
                    version_value: version.clone(),
                    url,
                    headers: HashMap::new(),
                    description: format!("URL path version probe: /{}/{}", version, stripped),
                });
            }
        }
        probes
    }

    /// Generate header-based version probes.
    pub fn generate_header_probes(&self) -> Vec<VersionProbe> {
        let mut probes = Vec::new();
        let endpoints = if self.config.known_endpoints.is_empty() {
            vec!["/api/users".to_string()]
        } else {
            self.config.known_endpoints.clone()
        };

        for version in &self.config.version_values {
            for header_name in VERSION_HEADERS {
                for endpoint in &endpoints {
                    let url = format!(
                        "{}/{}",
                        self.config.base_url,
                        endpoint.trim_start_matches('/')
                    );
                    let mut headers = HashMap::new();
                    headers.insert(header_name.to_string(), version.clone());
                    probes.push(VersionProbe {
                        scheme: VersioningScheme::Header,
                        version_value: version.clone(),
                        url,
                        headers,
                        description: format!("Header version probe: {}: {}", header_name, version),
                    });
                }
            }
        }
        probes
    }

    /// Generate query-parameter version probes.
    pub fn generate_query_param_probes(&self) -> Vec<VersionProbe> {
        let mut probes = Vec::new();
        let endpoints = if self.config.known_endpoints.is_empty() {
            vec!["/api/users".to_string()]
        } else {
            self.config.known_endpoints.clone()
        };

        for version in &self.config.version_values {
            for param_name in VERSION_QUERY_PARAMS {
                for endpoint in &endpoints {
                    let base = format!(
                        "{}/{}",
                        self.config.base_url,
                        endpoint.trim_start_matches('/')
                    );
                    let url = format!("{}?{}={}", base, param_name, version);
                    probes.push(VersionProbe {
                        scheme: VersioningScheme::QueryParam,
                        version_value: version.clone(),
                        url,
                        headers: HashMap::new(),
                        description: format!(
                            "Query param version probe: ?{}={}",
                            param_name, version
                        ),
                    });
                }
            }
        }
        probes
    }

    /// Generate subdomain-based version probes.
    pub fn generate_subdomain_probes(&self) -> Vec<VersionProbe> {
        let mut probes = Vec::new();
        let host = extract_host(&self.config.base_url);

        for version in &self.config.version_values {
            let subdomain_url = format!("https://{}.{}", version, host);
            probes.push(VersionProbe {
                scheme: VersioningScheme::Subdomain,
                version_value: version.clone(),
                url: subdomain_url,
                headers: HashMap::new(),
                description: format!("Subdomain version probe: {}.{}", version, host),
            });
        }
        probes
    }

    /// Generate content-type version probes (vendor media types).
    pub fn generate_content_type_probes(&self) -> Vec<VersionProbe> {
        let mut probes = Vec::new();
        let endpoints = if self.config.known_endpoints.is_empty() {
            vec!["/api/users".to_string()]
        } else {
            self.config.known_endpoints.clone()
        };

        for version in &self.config.version_values {
            for pattern in CONTENT_TYPE_PATTERNS {
                let content_type = pattern.replace("{version}", version);
                for endpoint in &endpoints {
                    let url = format!(
                        "{}/{}",
                        self.config.base_url,
                        endpoint.trim_start_matches('/')
                    );
                    let mut headers = HashMap::new();
                    headers.insert("Content-Type".to_string(), content_type.clone());
                    probes.push(VersionProbe {
                        scheme: VersioningScheme::ContentType,
                        version_value: version.clone(),
                        url,
                        headers,
                        description: format!("Content-Type version probe: {}", content_type),
                    });
                }
            }
        }
        probes
    }

    /// Generate Accept-header version probes.
    pub fn generate_accept_header_probes(&self) -> Vec<VersionProbe> {
        let mut probes = Vec::new();
        let endpoints = if self.config.known_endpoints.is_empty() {
            vec!["/api/users".to_string()]
        } else {
            self.config.known_endpoints.clone()
        };

        let accept_patterns = [
            "application/vnd.api.{version}+json",
            "application/vnd.company.{version}+json",
        ];

        for version in &self.config.version_values {
            for pattern in &accept_patterns {
                let accept_value = pattern.replace("{version}", version);
                for endpoint in &endpoints {
                    let url = format!(
                        "{}/{}",
                        self.config.base_url,
                        endpoint.trim_start_matches('/')
                    );
                    let mut headers = HashMap::new();
                    headers.insert("Accept".to_string(), accept_value.clone());
                    probes.push(VersionProbe {
                        scheme: VersioningScheme::AcceptHeader,
                        version_value: version.clone(),
                        url,
                        headers,
                        description: format!("Accept header version probe: {}", accept_value),
                    });
                }
            }
        }
        probes
    }

    /// Generate all probes across all configured schemes.
    pub fn generate_all_probes(&self) -> Vec<VersionProbe> {
        let mut probes = Vec::new();
        for scheme in &self.config.schemes {
            match scheme {
                VersioningScheme::UrlPath => probes.extend(self.generate_url_path_probes()),
                VersioningScheme::Header => probes.extend(self.generate_header_probes()),
                VersioningScheme::QueryParam => probes.extend(self.generate_query_param_probes()),
                VersioningScheme::Subdomain => probes.extend(self.generate_subdomain_probes()),
                VersioningScheme::ContentType => {
                    probes.extend(self.generate_content_type_probes());
                }
                VersioningScheme::AcceptHeader => {
                    probes.extend(self.generate_accept_header_probes());
                }
            }
        }
        probes
    }

    /// Generate attack probes for undocumented version discovery.
    pub fn generate_undocumented_version_probes(&self) -> Vec<AttackProbe> {
        let undocumented_versions = [
            "v0",
            "v99",
            "v100",
            "beta",
            "alpha",
            "canary",
            "internal",
            "staging",
            "dev",
            "preview",
            "experimental",
            "legacy",
            "deprecated",
            "unstable",
            "nightly",
            "next",
        ];
        let mut attacks = Vec::new();
        let endpoints = if self.config.known_endpoints.is_empty() {
            vec!["/api/users".to_string()]
        } else {
            self.config.known_endpoints.clone()
        };

        for version in &undocumented_versions {
            for endpoint in &endpoints {
                let stripped = endpoint.trim_start_matches('/');
                let url = format!("{}/{}/{}", self.config.base_url, version, stripped);
                attacks.push(AttackProbe {
                    category: AttackCategory::UndocumentedVersion,
                    probe: VersionProbe {
                        scheme: VersioningScheme::UrlPath,
                        version_value: version.to_string(),
                        url,
                        headers: HashMap::new(),
                        description: format!(
                            "Undocumented version probe: /{}/{}",
                            version, stripped
                        ),
                    },
                    risk_rationale: format!(
                        "Version '{}' may expose debug/internal endpoints without production security controls",
                        version
                    ),
                });
            }
        }
        attacks
    }

    /// Generate version rollback attack probes — forces older API version to bypass newer security controls.
    pub fn generate_rollback_probes(&self) -> Vec<AttackProbe> {
        let current = self.config.current_version.as_deref().unwrap_or("v2");
        let older_versions: Vec<&str> = VERSION_PROBES
            .iter()
            .copied()
            .filter(|v| version_ordinal(v) < version_ordinal(current))
            .collect();

        let mut attacks = Vec::new();
        let endpoints = if self.config.known_endpoints.is_empty() {
            vec!["/api/users".to_string()]
        } else {
            self.config.known_endpoints.clone()
        };

        for old_version in &older_versions {
            for endpoint in &endpoints {
                let stripped = endpoint.trim_start_matches('/');
                let url = format!("{}/{}/{}", self.config.base_url, old_version, stripped);
                attacks.push(AttackProbe {
                    category: AttackCategory::VersionRollback,
                    probe: VersionProbe {
                        scheme: VersioningScheme::UrlPath,
                        version_value: old_version.to_string(),
                        url,
                        headers: HashMap::new(),
                        description: format!(
                            "Version rollback: {} → {} for /{}",
                            current, old_version, stripped
                        ),
                    },
                    risk_rationale: format!(
                        "Downgrading from {} to {} may bypass security controls added in newer version",
                        current, old_version
                    ),
                });
            }
        }
        attacks
    }

    /// Generate mixed-version IDOR probes — accessing v1 endpoint with v2 auth context.
    pub fn generate_mixed_version_idor_probes(&self) -> Vec<AttackProbe> {
        let mut attacks = Vec::new();
        let endpoints = if self.config.known_endpoints.is_empty() {
            vec!["/api/users/1".to_string(), "/api/accounts/me".to_string()]
        } else {
            self.config.known_endpoints.clone()
        };

        let version_pairs = [("v1", "v2"), ("v2", "v1"), ("v1", "v3"), ("v2", "v3")];

        for (url_version, header_version) in &version_pairs {
            for endpoint in &endpoints {
                let stripped = endpoint.trim_start_matches('/');
                let url = format!("{}/{}/{}", self.config.base_url, url_version, stripped);
                let mut headers = HashMap::new();
                headers.insert("API-Version".to_string(), header_version.to_string());
                attacks.push(AttackProbe {
                    category: AttackCategory::MixedVersionIdor,
                    probe: VersionProbe {
                        scheme: VersioningScheme::UrlPath,
                        version_value: url_version.to_string(),
                        url,
                        headers,
                        description: format!(
                            "Mixed-version IDOR: URL={}, Header={}",
                            url_version, header_version
                        ),
                    },
                    risk_rationale: format!(
                        "URL uses {} but header claims {} — scope confusion may grant access to resources across version boundaries",
                        url_version, header_version
                    ),
                });
            }
        }
        attacks
    }

    /// Generate version header injection probes — test if a custom header overrides path versioning.
    pub fn generate_header_injection_probes(&self) -> Vec<AttackProbe> {
        let mut attacks = Vec::new();
        let endpoints = if self.config.known_endpoints.is_empty() {
            vec!["/api/users".to_string()]
        } else {
            self.config.known_endpoints.clone()
        };

        let injection_versions = ["v0", "v1", "internal", "beta", "legacy"];

        for injection_version in &injection_versions {
            for header_name in VERSION_HEADERS {
                for endpoint in &endpoints {
                    let stripped = endpoint.trim_start_matches('/');
                    let url = format!("{}/v2/{}", self.config.base_url, stripped);
                    let mut headers = HashMap::new();
                    headers.insert(header_name.to_string(), injection_version.to_string());
                    attacks.push(AttackProbe {
                        category: AttackCategory::VersionHeaderInjection,
                        probe: VersionProbe {
                            scheme: VersioningScheme::Header,
                            version_value: injection_version.to_string(),
                            url,
                            headers,
                            description: format!(
                                "Header injection: URL=/v2 but {}: {}",
                                header_name, injection_version
                            ),
                        },
                        risk_rationale: format!(
                            "Injecting {}: {} on /v2 path may override routing to older/unpatched version",
                            header_name, injection_version
                        ),
                    });
                }
            }
        }
        attacks
    }

    /// Generate API gateway bypass probes — test direct backend access skipping gateway version routing.
    pub fn generate_gateway_bypass_probes(&self) -> Vec<AttackProbe> {
        let mut attacks = Vec::new();
        let endpoints = if self.config.known_endpoints.is_empty() {
            vec!["/api/users".to_string()]
        } else {
            self.config.known_endpoints.clone()
        };

        let bypass_patterns = [
            ("{base}/internal/{endpoint}", "Direct /internal/ prefix"),
            ("{base}/api-internal/{endpoint}", "Internal API prefix"),
            ("{base}/backend/{endpoint}", "Direct backend prefix"),
            ("{base}/_/{endpoint}", "Underscore path bypass"),
            ("{base}/debug/{endpoint}", "Debug path bypass"),
        ];

        let bypass_headers: Vec<(String, String)> = vec![
            ("X-Forwarded-Host".to_string(), "internal".to_string()),
            ("X-Original-URL".to_string(), "/internal/api".to_string()),
            ("X-Rewrite-URL".to_string(), "/api/v1/admin".to_string()),
        ];

        for (pattern, desc) in &bypass_patterns {
            for endpoint in &endpoints {
                let stripped = endpoint.trim_start_matches('/');
                let url = pattern
                    .replace("{base}", &self.config.base_url)
                    .replace("{endpoint}", stripped);
                let mut headers = HashMap::new();
                for (k, v) in &bypass_headers {
                    headers.insert(k.clone(), v.clone());
                }
                attacks.push(AttackProbe {
                    category: AttackCategory::ApiGatewayBypass,
                    probe: VersionProbe {
                        scheme: VersioningScheme::UrlPath,
                        version_value: "bypass".to_string(),
                        url,
                        headers,
                        description: format!("Gateway bypass: {}", desc),
                    },
                    risk_rationale:
                        "Bypassing API gateway version routing may expose unversioned backend endpoints without access controls"
                            .to_string(),
                });
            }
        }
        attacks
    }

    /// Generate all attack probes across all categories.
    pub fn generate_all_attacks(&self) -> Vec<AttackProbe> {
        let mut attacks = Vec::new();
        attacks.extend(self.generate_undocumented_version_probes());
        attacks.extend(self.generate_rollback_probes());
        attacks.extend(self.generate_mixed_version_idor_probes());
        attacks.extend(self.generate_header_injection_probes());
        attacks.extend(self.generate_gateway_bypass_probes());
        attacks
    }
}

/// Compare two sets of versioned endpoints and produce a diff.
pub fn diff_versions(
    old_version: &str,
    old_endpoints: &[VersionedEndpoint],
    new_version: &str,
    new_endpoints: &[VersionedEndpoint],
) -> VersionDiff {
    let old_set: HashSet<(&str, &str)> = old_endpoints
        .iter()
        .map(|e| (e.path.as_str(), e.method.as_str()))
        .collect();
    let new_set: HashSet<(&str, &str)> = new_endpoints
        .iter()
        .map(|e| (e.path.as_str(), e.method.as_str()))
        .collect();

    let removed_in_new: Vec<VersionedEndpoint> = old_endpoints
        .iter()
        .filter(|e| !new_set.contains(&(e.path.as_str(), e.method.as_str())))
        .map(|e| VersionedEndpoint {
            path: e.path.clone(),
            method: e.method.clone(),
            version: old_version.to_string(),
        })
        .collect();

    let added_in_new: Vec<VersionedEndpoint> = new_endpoints
        .iter()
        .filter(|e| !old_set.contains(&(e.path.as_str(), e.method.as_str())))
        .map(|e| VersionedEndpoint {
            path: e.path.clone(),
            method: e.method.clone(),
            version: new_version.to_string(),
        })
        .collect();

    VersionDiff {
        old_version: old_version.to_string(),
        new_version: new_version.to_string(),
        removed_in_new,
        added_in_new,
    }
}

/// Extract host from a URL (strips scheme and trailing path).
pub fn extract_host(url: &str) -> String {
    let without_scheme = url
        .strip_prefix("https://")
        .or_else(|| url.strip_prefix("http://"))
        .unwrap_or(url);
    without_scheme
        .split('/')
        .next()
        .unwrap_or(without_scheme)
        .to_string()
}

/// Convert a version string to a numeric ordinal for comparison.
/// Numbered versions (v0-v10) get 0-10, named versions get high ordinals.
pub fn version_ordinal(version: &str) -> i32 {
    if let Some(stripped) = version.strip_prefix('v')
        && let Ok(n) = stripped.parse::<i32>()
    {
        return n;
    }
    match version {
        "alpha" => -3,
        "beta" => -2,
        "canary" => -1,
        "legacy" | "deprecated" => -10,
        "internal" | "dev" | "staging" => -5,
        "latest" | "edge" | "preview" | "experimental" | "unstable" => 1000,
        _ => 500,
    }
}

/// Classify which versioning scheme a response likely uses based on the probe that elicited it.
pub fn classify_scheme(probe: &VersionProbe) -> VersioningScheme {
    probe.scheme
}

/// Generate a GraphQL schema diff query for comparing types across versions.
pub fn graphql_schema_diff_queries(old_version: &str, new_version: &str) -> Vec<AttackProbe> {
    let introspection_query = r#"{ __schema { types { name fields { name type { name } } } } }"#;
    let mut probes = Vec::new();

    for (version, desc) in [(old_version, "old"), (new_version, "new")] {
        probes.push(AttackProbe {
            category: AttackCategory::GraphqlSchemaDiff,
            probe: VersionProbe {
                scheme: VersioningScheme::UrlPath,
                version_value: version.to_string(),
                url: format!("/{}/graphql", version),
                headers: HashMap::new(),
                description: format!(
                    "GraphQL introspection for {} version ({})",
                    desc, version
                ),
            },
            risk_rationale: format!(
                "Comparing {} ({}) vs {} ({}) schema may reveal security checks removed in migration",
                old_version,
                if desc == "old" { "this probe" } else { "other probe" },
                new_version,
                if desc == "new" { "this probe" } else { "other probe" },
            ),
        });
    }

    probes.push(AttackProbe {
        category: AttackCategory::GraphqlSchemaDiff,
        probe: VersionProbe {
            scheme: VersioningScheme::Header,
            version_value: old_version.to_string(),
            url: "/graphql".to_string(),
            headers: {
                let mut h = HashMap::new();
                h.insert("API-Version".to_string(), old_version.to_string());
                h
            },
            description: format!(
                "GraphQL introspection via header for version {}",
                old_version
            ),
        },
        risk_rationale: "Header-based version selection for GraphQL may bypass schema validation"
            .to_string(),
    });

    let _ = introspection_query;
    probes
}

/// Collect unique schemes from a set of probes.
pub fn unique_schemes(probes: &[VersionProbe]) -> HashSet<VersioningScheme> {
    probes.iter().map(|p| p.scheme).collect()
}

/// Collect unique version values from a set of probes.
pub fn unique_versions(probes: &[VersionProbe]) -> HashSet<String> {
    probes.iter().map(|p| p.version_value.clone()).collect()
}
