use aegis_protocol::finding::VulnerabilityClass;

use crate::cvss_scorer::{
    AttackComplexity, AttackVector, CvssMetrics, Impact, PrivilegesRequired, Scope, UserInteraction,
};

/// Maps a `VulnerabilityClass` to default CVSS v3.1 base metrics.
///
/// These represent typical worst-case base metrics for each vulnerability class
/// in a web application context. Context adjustments (authentication, WAF, etc.)
/// should be applied separately via `adjust_cvss_for_context`.
pub fn default_cvss_for_class(vuln_class: VulnerabilityClass) -> CvssMetrics {
    match vuln_class {
        VulnerabilityClass::SqlInjection => CvssMetrics {
            attack_vector: AttackVector::Network,
            attack_complexity: AttackComplexity::Low,
            privileges_required: PrivilegesRequired::None,
            user_interaction: UserInteraction::None,
            scope: Scope::Unchanged,
            confidentiality: Impact::High,
            integrity: Impact::High,
            availability: Impact::None,
        },
        VulnerabilityClass::CrossSiteScripting => CvssMetrics {
            attack_vector: AttackVector::Network,
            attack_complexity: AttackComplexity::Low,
            privileges_required: PrivilegesRequired::None,
            user_interaction: UserInteraction::Required,
            scope: Scope::Changed,
            confidentiality: Impact::Low,
            integrity: Impact::Low,
            availability: Impact::None,
        },
        VulnerabilityClass::CommandInjection => CvssMetrics {
            attack_vector: AttackVector::Network,
            attack_complexity: AttackComplexity::Low,
            privileges_required: PrivilegesRequired::None,
            user_interaction: UserInteraction::None,
            scope: Scope::Unchanged,
            confidentiality: Impact::High,
            integrity: Impact::High,
            availability: Impact::High,
        },
        VulnerabilityClass::PathTraversal => CvssMetrics {
            attack_vector: AttackVector::Network,
            attack_complexity: AttackComplexity::Low,
            privileges_required: PrivilegesRequired::None,
            user_interaction: UserInteraction::None,
            scope: Scope::Unchanged,
            confidentiality: Impact::High,
            integrity: Impact::None,
            availability: Impact::None,
        },
        VulnerabilityClass::ServerSideRequestForgery => CvssMetrics {
            attack_vector: AttackVector::Network,
            attack_complexity: AttackComplexity::Low,
            privileges_required: PrivilegesRequired::None,
            user_interaction: UserInteraction::None,
            scope: Scope::Changed,
            confidentiality: Impact::High,
            integrity: Impact::None,
            availability: Impact::None,
        },
        VulnerabilityClass::InsecureDeserialization => CvssMetrics {
            attack_vector: AttackVector::Network,
            attack_complexity: AttackComplexity::Low,
            privileges_required: PrivilegesRequired::None,
            user_interaction: UserInteraction::None,
            scope: Scope::Unchanged,
            confidentiality: Impact::High,
            integrity: Impact::High,
            availability: Impact::High,
        },
        VulnerabilityClass::BrokenAuthentication => CvssMetrics {
            attack_vector: AttackVector::Network,
            attack_complexity: AttackComplexity::Low,
            privileges_required: PrivilegesRequired::None,
            user_interaction: UserInteraction::None,
            scope: Scope::Unchanged,
            confidentiality: Impact::High,
            integrity: Impact::High,
            availability: Impact::None,
        },
        VulnerabilityClass::BrokenAuthorization => CvssMetrics {
            attack_vector: AttackVector::Network,
            attack_complexity: AttackComplexity::Low,
            privileges_required: PrivilegesRequired::Low,
            user_interaction: UserInteraction::None,
            scope: Scope::Unchanged,
            confidentiality: Impact::High,
            integrity: Impact::High,
            availability: Impact::None,
        },
        VulnerabilityClass::SecurityMisconfiguration => CvssMetrics {
            attack_vector: AttackVector::Network,
            attack_complexity: AttackComplexity::Low,
            privileges_required: PrivilegesRequired::None,
            user_interaction: UserInteraction::None,
            scope: Scope::Unchanged,
            confidentiality: Impact::Low,
            integrity: Impact::Low,
            availability: Impact::None,
        },
        VulnerabilityClass::SensitiveDataExposure => CvssMetrics {
            attack_vector: AttackVector::Network,
            attack_complexity: AttackComplexity::Low,
            privileges_required: PrivilegesRequired::None,
            user_interaction: UserInteraction::None,
            scope: Scope::Unchanged,
            confidentiality: Impact::High,
            integrity: Impact::None,
            availability: Impact::None,
        },
        VulnerabilityClass::ServerSideTemplateInjection => CvssMetrics {
            attack_vector: AttackVector::Network,
            attack_complexity: AttackComplexity::Low,
            privileges_required: PrivilegesRequired::None,
            user_interaction: UserInteraction::None,
            scope: Scope::Unchanged,
            confidentiality: Impact::High,
            integrity: Impact::High,
            availability: Impact::High,
        },
        VulnerabilityClass::HeaderInjection => CvssMetrics {
            attack_vector: AttackVector::Network,
            attack_complexity: AttackComplexity::Low,
            privileges_required: PrivilegesRequired::None,
            user_interaction: UserInteraction::None,
            scope: Scope::Unchanged,
            confidentiality: Impact::None,
            integrity: Impact::Low,
            availability: Impact::None,
        },
        VulnerabilityClass::OpenRedirect => CvssMetrics {
            attack_vector: AttackVector::Network,
            attack_complexity: AttackComplexity::Low,
            privileges_required: PrivilegesRequired::None,
            user_interaction: UserInteraction::Required,
            scope: Scope::Changed,
            confidentiality: Impact::Low,
            integrity: Impact::Low,
            availability: Impact::None,
        },
        VulnerabilityClass::CrlfInjection => CvssMetrics {
            attack_vector: AttackVector::Network,
            attack_complexity: AttackComplexity::Low,
            privileges_required: PrivilegesRequired::None,
            user_interaction: UserInteraction::None,
            scope: Scope::Unchanged,
            confidentiality: Impact::None,
            integrity: Impact::Low,
            availability: Impact::None,
        },
        VulnerabilityClass::KnownVulnerableDependency => CvssMetrics {
            attack_vector: AttackVector::Network,
            attack_complexity: AttackComplexity::Low,
            privileges_required: PrivilegesRequired::None,
            user_interaction: UserInteraction::None,
            scope: Scope::Unchanged,
            confidentiality: Impact::Low,
            integrity: Impact::Low,
            availability: Impact::Low,
        },
        VulnerabilityClass::InsufficientInputValidation => CvssMetrics {
            attack_vector: AttackVector::Network,
            attack_complexity: AttackComplexity::Low,
            privileges_required: PrivilegesRequired::None,
            user_interaction: UserInteraction::None,
            scope: Scope::Unchanged,
            confidentiality: Impact::Low,
            integrity: Impact::Low,
            availability: Impact::None,
        },
        VulnerabilityClass::NoSqlInjection => CvssMetrics {
            attack_vector: AttackVector::Network,
            attack_complexity: AttackComplexity::Low,
            privileges_required: PrivilegesRequired::None,
            user_interaction: UserInteraction::None,
            scope: Scope::Unchanged,
            confidentiality: Impact::High,
            integrity: Impact::High,
            availability: Impact::None,
        },
        VulnerabilityClass::XmlExternalEntity => CvssMetrics {
            attack_vector: AttackVector::Network,
            attack_complexity: AttackComplexity::Low,
            privileges_required: PrivilegesRequired::None,
            user_interaction: UserInteraction::None,
            scope: Scope::Changed,
            confidentiality: Impact::High,
            integrity: Impact::None,
            availability: Impact::None,
        },
        VulnerabilityClass::CrossOriginMisconfiguration => CvssMetrics {
            attack_vector: AttackVector::Network,
            attack_complexity: AttackComplexity::Low,
            privileges_required: PrivilegesRequired::None,
            user_interaction: UserInteraction::Required,
            scope: Scope::Changed,
            confidentiality: Impact::Low,
            integrity: Impact::Low,
            availability: Impact::None,
        },
        VulnerabilityClass::MissingSecurityHeader => CvssMetrics {
            attack_vector: AttackVector::Network,
            attack_complexity: AttackComplexity::Low,
            privileges_required: PrivilegesRequired::None,
            user_interaction: UserInteraction::None,
            scope: Scope::Unchanged,
            confidentiality: Impact::None,
            integrity: Impact::Low,
            availability: Impact::None,
        },
        VulnerabilityClass::JwtVulnerability => CvssMetrics {
            attack_vector: AttackVector::Network,
            attack_complexity: AttackComplexity::Low,
            privileges_required: PrivilegesRequired::None,
            user_interaction: UserInteraction::None,
            scope: Scope::Unchanged,
            confidentiality: Impact::High,
            integrity: Impact::High,
            availability: Impact::None,
        },
        VulnerabilityClass::HttpRequestSmuggling => CvssMetrics {
            attack_vector: AttackVector::Network,
            attack_complexity: AttackComplexity::High,
            privileges_required: PrivilegesRequired::None,
            user_interaction: UserInteraction::None,
            scope: Scope::Changed,
            confidentiality: Impact::High,
            integrity: Impact::High,
            availability: Impact::None,
        },
        VulnerabilityClass::RaceCondition => CvssMetrics {
            attack_vector: AttackVector::Network,
            attack_complexity: AttackComplexity::High,
            privileges_required: PrivilegesRequired::None,
            user_interaction: UserInteraction::None,
            scope: Scope::Unchanged,
            confidentiality: Impact::Low,
            integrity: Impact::High,
            availability: Impact::None,
        },
        VulnerabilityClass::SubdomainTakeover => CvssMetrics {
            attack_vector: AttackVector::Network,
            attack_complexity: AttackComplexity::Low,
            privileges_required: PrivilegesRequired::None,
            user_interaction: UserInteraction::None,
            scope: Scope::Changed,
            confidentiality: Impact::Low,
            integrity: Impact::Low,
            availability: Impact::None,
        },
        VulnerabilityClass::PrototypePollution => CvssMetrics {
            attack_vector: AttackVector::Network,
            attack_complexity: AttackComplexity::Low,
            privileges_required: PrivilegesRequired::None,
            user_interaction: UserInteraction::None,
            scope: Scope::Unchanged,
            confidentiality: Impact::Low,
            integrity: Impact::High,
            availability: Impact::None,
        },
        VulnerabilityClass::GraphQlAbuse => CvssMetrics {
            attack_vector: AttackVector::Network,
            attack_complexity: AttackComplexity::Low,
            privileges_required: PrivilegesRequired::None,
            user_interaction: UserInteraction::None,
            scope: Scope::Unchanged,
            confidentiality: Impact::Low,
            integrity: Impact::Low,
            availability: Impact::Low,
        },
        VulnerabilityClass::CloudMisconfiguration => CvssMetrics {
            attack_vector: AttackVector::Network,
            attack_complexity: AttackComplexity::Low,
            privileges_required: PrivilegesRequired::None,
            user_interaction: UserInteraction::None,
            scope: Scope::Unchanged,
            confidentiality: Impact::Low,
            integrity: Impact::Low,
            availability: Impact::None,
        },
        VulnerabilityClass::Clickjacking => CvssMetrics {
            attack_vector: AttackVector::Network,
            attack_complexity: AttackComplexity::Low,
            privileges_required: PrivilegesRequired::None,
            user_interaction: UserInteraction::Required,
            scope: Scope::Changed,
            confidentiality: Impact::None,
            integrity: Impact::Low,
            availability: Impact::None,
        },
        VulnerabilityClass::CachePoisoning => CvssMetrics {
            attack_vector: AttackVector::Network,
            attack_complexity: AttackComplexity::High,
            privileges_required: PrivilegesRequired::None,
            user_interaction: UserInteraction::None,
            scope: Scope::Changed,
            confidentiality: Impact::Low,
            integrity: Impact::High,
            availability: Impact::None,
        },
        VulnerabilityClass::HostHeaderInjection => CvssMetrics {
            attack_vector: AttackVector::Network,
            attack_complexity: AttackComplexity::Low,
            privileges_required: PrivilegesRequired::None,
            user_interaction: UserInteraction::None,
            scope: Scope::Unchanged,
            confidentiality: Impact::None,
            integrity: Impact::Low,
            availability: Impact::None,
        },
        VulnerabilityClass::InsecureDirectObjectReference => CvssMetrics {
            attack_vector: AttackVector::Network,
            attack_complexity: AttackComplexity::Low,
            privileges_required: PrivilegesRequired::Low,
            user_interaction: UserInteraction::None,
            scope: Scope::Unchanged,
            confidentiality: Impact::High,
            integrity: Impact::High,
            availability: Impact::None,
        },
        VulnerabilityClass::InformationDisclosure => CvssMetrics {
            attack_vector: AttackVector::Network,
            attack_complexity: AttackComplexity::Low,
            privileges_required: PrivilegesRequired::None,
            user_interaction: UserInteraction::None,
            scope: Scope::Unchanged,
            confidentiality: Impact::High,
            integrity: Impact::None,
            availability: Impact::None,
        },
        VulnerabilityClass::WeakCryptography => CvssMetrics {
            attack_vector: AttackVector::Network,
            attack_complexity: AttackComplexity::High,
            privileges_required: PrivilegesRequired::None,
            user_interaction: UserInteraction::None,
            scope: Scope::Unchanged,
            confidentiality: Impact::High,
            integrity: Impact::None,
            availability: Impact::None,
        },
        VulnerabilityClass::MassAssignment => CvssMetrics {
            attack_vector: AttackVector::Network,
            attack_complexity: AttackComplexity::Low,
            privileges_required: PrivilegesRequired::Low,
            user_interaction: UserInteraction::None,
            scope: Scope::Unchanged,
            confidentiality: Impact::None,
            integrity: Impact::High,
            availability: Impact::None,
        },
    }
}
