/// Cargo.lock with a package known to have vulnerabilities (hyper 0.14.0).
pub fn cargo_lock_with_vuln() -> &'static str {
    r#"# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "bytes"
version = "1.5.0"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "hyper"
version = "0.14.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "bytes",
 "http",
 "tokio",
]

[[package]]
name = "http"
version = "0.2.11"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "tokio"
version = "1.35.0"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "my-app"
version = "0.1.0"
dependencies = [
 "hyper",
]
"#
}

/// npm package-lock.json v2 format with a vulnerable dependency (lodash 4.17.20).
pub fn package_lock_v2() -> &'static str {
    r#"{
  "name": "my-app",
  "version": "1.0.0",
  "lockfileVersion": 2,
  "requires": true,
  "packages": {
    "": {
      "name": "my-app",
      "version": "1.0.0",
      "dependencies": {
        "express": "^4.18.0",
        "lodash": "^4.17.20"
      }
    },
    "node_modules/express": {
      "version": "4.18.2",
      "resolved": "https://registry.npmjs.org/express/-/express-4.18.2.tgz"
    },
    "node_modules/lodash": {
      "version": "4.17.20",
      "resolved": "https://registry.npmjs.org/lodash/-/lodash-4.17.20.tgz"
    }
  },
  "dependencies": {
    "express": {
      "version": "4.18.2"
    },
    "lodash": {
      "version": "4.17.20"
    }
  }
}"#
}

/// poetry.lock with a vulnerable dependency (pyyaml 5.3.1).
pub fn poetry_lock() -> &'static str {
    r#"[[package]]
name = "pyyaml"
version = "5.3.1"
description = "YAML parser and emitter for Python"
category = "main"
optional = false
python-versions = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*"

[[package]]
name = "requests"
version = "2.28.0"
description = "Python HTTP for Humans."
category = "main"
optional = false
python-versions = ">=3.7, <4"

[metadata]
python-versions = "^3.9"
content-hash = "abc123"
"#
}

/// Gemfile.lock with nested dependencies.
pub fn gemfile_lock() -> &'static str {
    r#"GEM
  remote: https://rubygems.org/
  specs:
    actionpack (6.1.4)
      actionview (= 6.1.4)
      activesupport (= 6.1.4)
      rack (~> 2.0, >= 2.0.9)
    actionview (6.1.4)
      activesupport (= 6.1.4)
    activesupport (6.1.4)
      concurrent-ruby (~> 1.0, >= 1.0.2)
    concurrent-ruby (1.1.9)
    nokogiri (1.12.5)
      racc (~> 1.4)
    racc (1.6.0)
    rack (2.2.3)
    rails (6.1.4)
      actionpack (= 6.1.4)

PLATFORMS
  ruby

DEPENDENCIES
  rails (~> 6.1)
  nokogiri (~> 1.12)

BUNDLED WITH
   2.2.33
"#
}

/// go.sum with a vulnerable dependency.
pub fn go_sum() -> &'static str {
    r#"github.com/gin-gonic/gin v1.7.0 h1:jGB9xAJQ12AIGNB4HguQmfSAR49tz3FlAkEbEHG+3A=
github.com/gin-gonic/gin v1.7.0/go.mod h1:jD2toBW3GZUr5UMcdrwQA10I7RuaFOl/SGeDjXkfUtY=
golang.org/x/crypto v0.0.0-20210817164053-32db794688a5 h1:HWj/xjn4GgQCfNAMi2l=
golang.org/x/crypto v0.0.0-20210817164053-32db794688a5/go.mod h1:GvvjBRRGRdwPK5ydB=
golang.org/x/text v0.3.7 h1:olpwvP2KacW1ZWvsR7uQhoyTYvKAupfQrRGBFM352Gk=
golang.org/x/text v0.3.7/go.mod h1:u+2+/6zg+i71rQMx5EYifcz6MCKuco9NR6JIITiCfzQ=
"#
}

/// Express.js source with route handlers.
pub fn express_source() -> &'static str {
    r#"const express = require('express');
const app = express();

app.get('/api/users', (req, res) => {
    res.json({ users: [] });
});

app.post('/api/users', (req, res) => {
    res.status(201).json({ id: 1 });
});

app.get('/api/users/:id', (req, res) => {
    res.json({ id: req.params.id });
});

app.put('/api/users/:id', (req, res) => {
    res.json({ updated: true });
});

app.delete('/api/users/:id', (req, res) => {
    res.status(204).send();
});

app.get('/api/search', (req, res) => {
    res.json({ results: [] });
});

app.post('/api/login', (req, res) => {
    res.json({ token: 'fake-jwt' });
});

app.get('/health', (req, res) => {
    res.send('ok');
});

module.exports = app;
"#
}

/// Flask source with route decorators.
pub fn flask_source() -> &'static str {
    r#"from flask import Flask, request, jsonify

app = Flask(__name__)

@app.route('/api/users', methods=['GET'])
def list_users():
    return jsonify(users=[])

@app.route('/api/users', methods=['POST'])
def create_user():
    return jsonify(id=1), 201

@app.route('/api/users/<int:user_id>', methods=['GET'])
def get_user(user_id):
    return jsonify(id=user_id)

@app.route('/api/search', methods=['GET'])
def search():
    q = request.args.get('q', '')
    return jsonify(results=[], query=q)

@app.route('/api/upload', methods=['POST'])
def upload():
    return jsonify(status='uploaded')

@app.route('/health')
def health():
    return 'ok'
"#
}

/// FastAPI source with route decorators.
pub fn fastapi_source() -> &'static str {
    r#"from fastapi import FastAPI, Query

app = FastAPI()

@app.get("/api/items")
def list_items():
    return {"items": []}

@app.post("/api/items")
def create_item():
    return {"id": 1}

@app.get("/api/items/{item_id}")
def get_item(item_id: int):
    return {"id": item_id}

@app.get("/api/search")
def search(q: str = Query("")):
    return {"results": [], "query": q}

@app.post("/api/upload")
def upload():
    return {"status": "uploaded"}

@app.get("/health")
def health():
    return "ok"
"#
}

/// Django urlconf with path() calls.
pub fn django_source() -> &'static str {
    r#"from django.urls import path
from . import views

urlpatterns = [
    path('api/users/', views.user_list, name='user-list'),
    path('api/users/<int:pk>/', views.user_detail, name='user-detail'),
    path('api/search/', views.search, name='search'),
    path('api/login/', views.login, name='login'),
    path('api/upload/', views.upload, name='upload'),
    path('api/config/', views.config, name='config'),
    path('health/', views.health, name='health'),
]
"#
}

/// Spring controller with mapping annotations.
pub fn spring_source() -> &'static str {
    r#"package com.example.api;

import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api")
public class UserController {

    @GetMapping("/users")
    public List<User> listUsers() {
        return userService.findAll();
    }

    @PostMapping("/users")
    public User createUser(@RequestBody User user) {
        return userService.save(user);
    }

    @GetMapping("/users/{id}")
    public User getUser(@PathVariable Long id) {
        return userService.findById(id);
    }

    @PutMapping("/users/{id}")
    public User updateUser(@PathVariable Long id, @RequestBody User user) {
        return userService.update(id, user);
    }

    @DeleteMapping("/users/{id}")
    public void deleteUser(@PathVariable Long id) {
        userService.delete(id);
    }

    @GetMapping("/search")
    public SearchResult search(@RequestParam String q) {
        return searchService.search(q);
    }

    @PostMapping("/login")
    public TokenResponse login(@RequestBody LoginRequest req) {
        return authService.authenticate(req);
    }
}
"#
}

/// OpenAPI 3.0 JSON spec with ~10 endpoints.
pub fn openapi_spec() -> &'static str {
    r#"{
  "openapi": "3.0.0",
  "info": {
    "title": "Test API",
    "version": "1.0.0"
  },
  "paths": {
    "/api/users": {
      "get": {
        "operationId": "listUsers",
        "parameters": [
          {"name": "page", "in": "query", "schema": {"type": "integer"}},
          {"name": "limit", "in": "query", "schema": {"type": "integer"}}
        ],
        "responses": {"200": {"description": "OK"}}
      },
      "post": {
        "operationId": "createUser",
        "responses": {"201": {"description": "Created"}}
      }
    },
    "/api/users/{id}": {
      "get": {
        "operationId": "getUser",
        "parameters": [
          {"name": "id", "in": "path", "required": true, "schema": {"type": "integer"}}
        ],
        "responses": {"200": {"description": "OK"}}
      },
      "put": {
        "operationId": "updateUser",
        "parameters": [
          {"name": "id", "in": "path", "required": true, "schema": {"type": "integer"}}
        ],
        "responses": {"200": {"description": "OK"}}
      },
      "delete": {
        "operationId": "deleteUser",
        "parameters": [
          {"name": "id", "in": "path", "required": true, "schema": {"type": "integer"}}
        ],
        "responses": {"204": {"description": "No Content"}}
      }
    },
    "/api/search": {
      "get": {
        "operationId": "search",
        "parameters": [
          {"name": "q", "in": "query", "required": true, "schema": {"type": "string"}},
          {"name": "category", "in": "query", "schema": {"type": "string"}}
        ],
        "responses": {"200": {"description": "OK"}}
      }
    },
    "/api/login": {
      "post": {
        "operationId": "login",
        "responses": {"200": {"description": "OK"}}
      }
    },
    "/api/upload": {
      "post": {
        "operationId": "upload",
        "parameters": [
          {"name": "X-Api-Key", "in": "header", "required": true, "schema": {"type": "string"}}
        ],
        "responses": {"200": {"description": "OK"}}
      }
    },
    "/api/config": {
      "get": {
        "operationId": "getConfig",
        "responses": {"200": {"description": "OK"}}
      }
    },
    "/api/export": {
      "get": {
        "operationId": "export",
        "parameters": [
          {"name": "format", "in": "query", "schema": {"type": "string"}},
          {"name": "token", "in": "header", "schema": {"type": "string"}}
        ],
        "responses": {"200": {"description": "OK"}}
      }
    },
    "/health": {
      "get": {
        "operationId": "health",
        "responses": {"200": {"description": "OK"}}
      }
    }
  }
}"#
}

/// Full GraphQL introspection response JSON.
pub fn graphql_introspection_response() -> &'static str {
    r#"{
  "data": {
    "__schema": {
      "queryType": {"name": "Query"},
      "mutationType": {"name": "Mutation"},
      "types": [
        {
          "kind": "OBJECT",
          "name": "Query",
          "fields": [
            {"name": "user", "args": [{"name": "id", "type": {"name": "ID"}}]},
            {"name": "users", "args": [{"name": "limit", "type": {"name": "Int"}}]},
            {"name": "search", "args": [{"name": "query", "type": {"name": "String"}}]},
            {"name": "product", "args": [{"name": "id", "type": {"name": "ID"}}]},
            {"name": "orders", "args": []}
          ]
        },
        {
          "kind": "OBJECT",
          "name": "Mutation",
          "fields": [
            {"name": "createUser", "args": [{"name": "input", "type": {"name": "CreateUserInput"}}]},
            {"name": "updateUser", "args": [{"name": "id", "type": {"name": "ID"}}, {"name": "input", "type": {"name": "UpdateUserInput"}}]},
            {"name": "deleteUser", "args": [{"name": "id", "type": {"name": "ID"}}]}
          ]
        },
        {
          "kind": "OBJECT",
          "name": "User",
          "fields": [
            {"name": "id", "args": []},
            {"name": "name", "args": []},
            {"name": "email", "args": []},
            {"name": "role", "args": []}
          ]
        },
        {
          "kind": "OBJECT",
          "name": "Product",
          "fields": [
            {"name": "id", "args": []},
            {"name": "name", "args": []},
            {"name": "price", "args": []}
          ]
        },
        {
          "kind": "INPUT_OBJECT",
          "name": "CreateUserInput",
          "inputFields": [
            {"name": "name", "type": {"name": "String"}},
            {"name": "email", "type": {"name": "String"}}
          ]
        },
        {
          "kind": "INPUT_OBJECT",
          "name": "UpdateUserInput",
          "inputFields": [
            {"name": "name", "type": {"name": "String"}},
            {"name": "email", "type": {"name": "String"}}
          ]
        }
      ]
    }
  }
}"#
}

/// GraphQL SDL schema string.
pub fn graphql_sdl() -> &'static str {
    r#"type Query {
  user(id: ID!): User
  users(limit: Int): [User!]!
  search(query: String!): [SearchResult!]!
  product(id: ID!): Product
  orders: [Order!]!
}

type Mutation {
  createUser(input: CreateUserInput!): User!
  updateUser(id: ID!, input: UpdateUserInput!): User!
  deleteUser(id: ID!): Boolean!
}

type User {
  id: ID!
  name: String!
  email: String!
  role: Role!
}

type Product {
  id: ID!
  name: String!
  price: Float!
}

type Order {
  id: ID!
  userId: ID!
  total: Float!
}

union SearchResult = User | Product

input CreateUserInput {
  name: String!
  email: String!
}

input UpdateUserInput {
  name: String
  email: String
}

enum Role {
  ADMIN
  USER
  MODERATOR
}
"#
}

/// BusinessContext JSON with excluded, critical, and PII endpoints.
pub fn business_context_json() -> &'static str {
    r#"{
  "excluded_endpoints": [
    "/health",
    "/metrics",
    "/api/docs"
  ],
  "critical_assets": [
    "/api/login",
    "/api/users",
    "/api/config"
  ],
  "pii_endpoints": [
    "/api/users",
    "/api/users/{id}",
    "/api/export"
  ],
  "known_issues": [
    {
      "endpoint": "/api/search",
      "class": "SqlInjection",
      "status": "accepted_risk",
      "notes": "Parameterized queries deployed in v2.1"
    }
  ]
}"#
}
