use std::collections::{HashMap, HashSet};
use std::fmt;

use serde::{Deserialize, Serialize};

use crate::util::timestamp_ms;

/// State machine phases for the autonomous recon cycle.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ReconPhase {
    Discover,
    Enumerate,
    Correlate,
    Assess,
    Report,
}

impl fmt::Display for ReconPhase {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Discover => write!(f, "Discover"),
            Self::Enumerate => write!(f, "Enumerate"),
            Self::Correlate => write!(f, "Correlate"),
            Self::Assess => write!(f, "Assess"),
            Self::Report => write!(f, "Report"),
        }
    }
}

impl ReconPhase {
    pub fn next(self) -> Self {
        match self {
            Self::Discover => Self::Enumerate,
            Self::Enumerate => Self::Correlate,
            Self::Correlate => Self::Assess,
            Self::Assess => Self::Report,
            Self::Report => Self::Discover,
        }
    }
}

/// Classification of intelligence sources the recon engine can query.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum IntelSource {
    WebSearch,
    Dns,
    Whois,
    CertificateTransparency,
    SocialMedia,
    CodeRepository,
    PasteSite,
    DarkWeb,
    JobPostings,
    PublicFilings,
}

impl fmt::Display for IntelSource {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let label = match self {
            Self::WebSearch => "Web Search",
            Self::Dns => "DNS",
            Self::Whois => "WHOIS",
            Self::CertificateTransparency => "Certificate Transparency",
            Self::SocialMedia => "Social Media",
            Self::CodeRepository => "Code Repository",
            Self::PasteSite => "Paste Site",
            Self::DarkWeb => "Dark Web",
            Self::JobPostings => "Job Postings",
            Self::PublicFilings => "Public Filings",
        };
        write!(f, "{label}")
    }
}

/// A single piece of discovered intelligence.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IntelFinding {
    pub id: u64,
    pub finding_type: FindingType,
    pub value: String,
    pub source: IntelSource,
    pub confidence: f64,
    pub timestamp_ms: u64,
    pub parent_id: Option<u64>,
    pub metadata: HashMap<String, String>,
}

/// Types of intelligence the recon engine can discover.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum FindingType {
    Domain,
    Subdomain,
    IpAddress,
    EmailAddress,
    PersonName,
    Username,
    Organization,
    Technology,
    OpenPort,
    Certificate,
    Secret,
    ApiEndpoint,
    SocialProfile,
    Document,
    CodeRepo,
    Credential,
}

impl fmt::Display for FindingType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let label = match self {
            Self::Domain => "Domain",
            Self::Subdomain => "Subdomain",
            Self::IpAddress => "IP Address",
            Self::EmailAddress => "Email Address",
            Self::PersonName => "Person Name",
            Self::Username => "Username",
            Self::Organization => "Organization",
            Self::Technology => "Technology",
            Self::OpenPort => "Open Port",
            Self::Certificate => "Certificate",
            Self::Secret => "Secret",
            Self::ApiEndpoint => "API Endpoint",
            Self::SocialProfile => "Social Profile",
            Self::Document => "Document",
            Self::CodeRepo => "Code Repository",
            Self::Credential => "Credential",
        };
        write!(f, "{label}")
    }
}

/// A search query generated by the LLM or derived from findings.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReconQuery {
    pub query_text: String,
    pub source: IntelSource,
    pub priority: f64,
    pub rationale: String,
    pub derived_from: Option<u64>,
}

/// Configuration for the autonomous recon controller.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReconConfig {
    pub target: String,
    pub max_iterations: usize,
    pub convergence_threshold: usize,
    pub max_findings: usize,
    pub enabled_sources: HashSet<IntelSource>,
    pub max_depth: usize,
    pub timeout_secs: u64,
}

impl Default for ReconConfig {
    fn default() -> Self {
        let mut sources = HashSet::new();
        sources.insert(IntelSource::WebSearch);
        sources.insert(IntelSource::Dns);
        sources.insert(IntelSource::Whois);
        sources.insert(IntelSource::CertificateTransparency);
        sources.insert(IntelSource::CodeRepository);
        Self {
            target: String::new(),
            max_iterations: 10,
            convergence_threshold: 3,
            max_findings: 500,
            enabled_sources: sources,
            max_depth: 5,
            timeout_secs: 300,
        }
    }
}

impl ReconConfig {
    pub fn with_target(mut self, target: &str) -> Self {
        self.target = target.to_string();
        self
    }

    pub fn with_max_iterations(mut self, n: usize) -> Self {
        self.max_iterations = n;
        self
    }

    pub fn with_convergence_threshold(mut self, n: usize) -> Self {
        self.convergence_threshold = n;
        self
    }

    pub fn with_all_sources(mut self) -> Self {
        self.enabled_sources.insert(IntelSource::WebSearch);
        self.enabled_sources.insert(IntelSource::Dns);
        self.enabled_sources.insert(IntelSource::Whois);
        self.enabled_sources
            .insert(IntelSource::CertificateTransparency);
        self.enabled_sources.insert(IntelSource::SocialMedia);
        self.enabled_sources.insert(IntelSource::CodeRepository);
        self.enabled_sources.insert(IntelSource::PasteSite);
        self.enabled_sources.insert(IntelSource::DarkWeb);
        self.enabled_sources.insert(IntelSource::JobPostings);
        self.enabled_sources.insert(IntelSource::PublicFilings);
        self
    }
}

/// Structured intelligence report produced at the end of a recon cycle.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IntelReport {
    pub target: String,
    pub findings: Vec<IntelFinding>,
    pub total_queries_executed: usize,
    pub iterations_completed: usize,
    pub convergence_reached: bool,
    pub phase_durations_ms: HashMap<String, u64>,
    pub source_counts: HashMap<String, usize>,
    pub finding_type_counts: HashMap<String, usize>,
    pub generated_at_ms: u64,
    pub confidence_summary: ConfidenceSummary,
}

/// Aggregated confidence statistics for the report.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConfidenceSummary {
    pub mean: f64,
    pub median: f64,
    pub high_confidence_count: usize,
    pub low_confidence_count: usize,
}

impl ConfidenceSummary {
    pub fn from_findings(findings: &[IntelFinding]) -> Self {
        if findings.is_empty() {
            return Self {
                mean: 0.0,
                median: 0.0,
                high_confidence_count: 0,
                low_confidence_count: 0,
            };
        }
        let mut confs: Vec<f64> = findings.iter().map(|f| f.confidence).collect();
        confs.sort_by(|a, b| a.partial_cmp(b).unwrap_or(std::cmp::Ordering::Equal));
        let sum: f64 = confs.iter().sum();
        let mean = sum / confs.len() as f64;
        let median = if confs.len() % 2 == 0 {
            let mid = confs.len() / 2;
            (confs[mid - 1] + confs[mid]) / 2.0
        } else {
            confs[confs.len() / 2]
        };
        let high_confidence_count = confs.iter().filter(|&&c| c >= 0.8).count();
        let low_confidence_count = confs.iter().filter(|&&c| c < 0.4).count();
        Self {
            mean,
            median,
            high_confidence_count,
            low_confidence_count,
        }
    }
}

/// LLM prompt builder for generating recon queries based on current state.
#[derive(Debug)]
pub struct ReconPromptBuilder {
    target: String,
    current_findings: Vec<IntelFinding>,
    phase: ReconPhase,
}

impl ReconPromptBuilder {
    pub fn new(target: &str, phase: ReconPhase) -> Self {
        Self {
            target: target.to_string(),
            current_findings: Vec::new(),
            phase,
        }
    }

    pub fn with_findings(mut self, findings: Vec<IntelFinding>) -> Self {
        self.current_findings = findings;
        self
    }

    pub fn build_prompt(&self) -> String {
        let finding_summary = self.summarize_findings();
        format!(
            "<role>You are an expert OSINT investigator performing autonomous reconnaissance.</role>\n\
             <task>\n\
             Target: {target}\n\
             Current Phase: {phase}\n\
             Findings So Far: {count}\n\
             \n\
             {summary}\n\
             \n\
             Generate the next set of search queries to discover more intelligence about this target.\n\
             For each query, specify:\n\
             - The search query text\n\
             - Which source to query (WebSearch, Dns, Whois, CertificateTransparency, SocialMedia, CodeRepository, PasteSite)\n\
             - Priority (0.0-1.0) based on likely payoff\n\
             - Brief rationale for why this query is promising\n\
             </task>\n\
             <output_format>\n\
             <query source=\"SOURCE\" priority=\"PRIORITY\">\n\
             <text>QUERY_TEXT</text>\n\
             <rationale>RATIONALE</rationale>\n\
             </query>\n\
             </output_format>",
            target = self.target,
            phase = self.phase,
            count = self.current_findings.len(),
            summary = finding_summary,
        )
    }

    fn summarize_findings(&self) -> String {
        if self.current_findings.is_empty() {
            return "No findings yet. Start with broad discovery.".to_string();
        }
        let mut by_type: HashMap<String, Vec<&str>> = HashMap::new();
        for f in &self.current_findings {
            by_type
                .entry(f.finding_type.to_string())
                .or_default()
                .push(&f.value);
        }
        let mut lines = Vec::new();
        for (ftype, values) in &by_type {
            let preview: Vec<&str> = values.iter().take(5).copied().collect();
            let suffix = if values.len() > 5 {
                format!(" (+{} more)", values.len() - 5)
            } else {
                String::new()
            };
            lines.push(format!("- {ftype}: {}{suffix}", preview.join(", ")));
        }
        lines.join("\n")
    }
}

/// Parses LLM-generated queries from XML response text.
pub fn parse_recon_queries(response: &str) -> Vec<ReconQuery> {
    let mut queries = Vec::new();
    let mut remaining = response;

    while let Some(start) = remaining.find("<query ") {
        let after_tag = &remaining[start..];
        let Some(end) = after_tag.find("</query>") else {
            break;
        };
        let block = &after_tag[..end + 8];
        if let Some(q) = parse_single_query(block) {
            queries.push(q);
        }
        remaining = &after_tag[end + 8..];
    }

    queries.sort_by(|a, b| {
        b.priority
            .partial_cmp(&a.priority)
            .unwrap_or(std::cmp::Ordering::Equal)
    });
    queries
}

fn parse_single_query(block: &str) -> Option<ReconQuery> {
    let source = extract_attribute(block, "source")?;
    let priority: f64 = extract_attribute(block, "priority")?.parse().ok()?;
    let text = extract_tag_content(block, "text")?;
    let rationale = extract_tag_content(block, "rationale").unwrap_or_default();
    let intel_source = parse_intel_source(&source)?;

    Some(ReconQuery {
        query_text: text,
        source: intel_source,
        priority: priority.clamp(0.0, 1.0),
        rationale,
        derived_from: None,
    })
}

fn extract_attribute(block: &str, attr: &str) -> Option<String> {
    let pattern = format!("{attr}=\"");
    let start = block.find(&pattern)?;
    let after = &block[start + pattern.len()..];
    let end = after.find('"')?;
    Some(after[..end].to_string())
}

fn extract_tag_content(block: &str, tag: &str) -> Option<String> {
    let open = format!("<{tag}>");
    let close = format!("</{tag}>");
    let start = block.find(&open)?;
    let after = &block[start + open.len()..];
    let end = after.find(&close)?;
    Some(after[..end].trim().to_string())
}

fn parse_intel_source(s: &str) -> Option<IntelSource> {
    match s {
        "WebSearch" => Some(IntelSource::WebSearch),
        "Dns" | "DNS" => Some(IntelSource::Dns),
        "Whois" | "WHOIS" => Some(IntelSource::Whois),
        "CertificateTransparency" | "CT" => Some(IntelSource::CertificateTransparency),
        "SocialMedia" => Some(IntelSource::SocialMedia),
        "CodeRepository" | "GitHub" => Some(IntelSource::CodeRepository),
        "PasteSite" | "Pastebin" => Some(IntelSource::PasteSite),
        "DarkWeb" => Some(IntelSource::DarkWeb),
        "JobPostings" => Some(IntelSource::JobPostings),
        "PublicFilings" => Some(IntelSource::PublicFilings),
        _ => None,
    }
}

/// The autonomous recon controller state machine.
#[derive(Debug)]
pub struct AutonomousReconController {
    config: ReconConfig,
    phase: ReconPhase,
    iteration: usize,
    findings: Vec<IntelFinding>,
    seen_values: HashSet<String>,
    next_id: u64,
    queries_executed: usize,
    no_new_findings_streak: usize,
    phase_start_ms: u64,
    phase_durations_ms: HashMap<String, u64>,
}

impl AutonomousReconController {
    pub fn new(config: ReconConfig) -> Self {
        Self {
            config,
            phase: ReconPhase::Discover,
            iteration: 0,
            findings: Vec::new(),
            seen_values: HashSet::new(),
            next_id: 1,
            queries_executed: 0,
            no_new_findings_streak: 0,
            phase_start_ms: timestamp_ms(),
            phase_durations_ms: HashMap::new(),
        }
    }

    pub fn phase(&self) -> ReconPhase {
        self.phase
    }

    pub fn iteration(&self) -> usize {
        self.iteration
    }

    pub fn findings(&self) -> &[IntelFinding] {
        &self.findings
    }

    pub fn finding_count(&self) -> usize {
        self.findings.len()
    }

    pub fn has_converged(&self) -> bool {
        self.no_new_findings_streak >= self.config.convergence_threshold
    }

    pub fn is_complete(&self) -> bool {
        self.has_converged()
            || self.iteration >= self.config.max_iterations
            || self.findings.len() >= self.config.max_findings
    }

    /// Build the LLM prompt for the current phase.
    pub fn build_prompt(&self) -> String {
        ReconPromptBuilder::new(&self.config.target, self.phase)
            .with_findings(self.findings.clone())
            .build_prompt()
    }

    /// Ingest LLM response, extract queries, and return them ranked by priority.
    pub fn process_llm_response(&mut self, response: &str) -> Vec<ReconQuery> {
        let queries = parse_recon_queries(response);
        let filtered: Vec<ReconQuery> = queries
            .into_iter()
            .filter(|q| self.config.enabled_sources.contains(&q.source))
            .collect();
        self.queries_executed += filtered.len();
        filtered
    }

    /// Record findings from executing queries. Returns count of new (unseen) findings.
    pub fn ingest_findings(&mut self, new_findings: Vec<IntelFinding>) -> usize {
        let mut new_count = 0;
        for mut finding in new_findings {
            let dedup_key = format!("{}:{}", finding.finding_type, finding.value);
            if self.seen_values.contains(&dedup_key) {
                continue;
            }
            if self.findings.len() >= self.config.max_findings {
                break;
            }
            finding.id = self.next_id;
            self.next_id += 1;
            finding.timestamp_ms = timestamp_ms();
            self.seen_values.insert(dedup_key);
            self.findings.push(finding);
            new_count += 1;
        }

        if new_count == 0 {
            self.no_new_findings_streak += 1;
        } else {
            self.no_new_findings_streak = 0;
        }
        new_count
    }

    /// Advance the state machine to the next phase.
    pub fn advance_phase(&mut self) {
        let now = timestamp_ms();
        let elapsed = now.saturating_sub(self.phase_start_ms);
        self.phase_durations_ms
            .insert(self.phase.to_string(), elapsed);
        self.phase = self.phase.next();
        self.phase_start_ms = now;
        if self.phase == ReconPhase::Discover {
            self.iteration += 1;
        }
    }

    /// Run one full cycle: Discover → Enumerate → Correlate → Assess → Report.
    pub fn run_cycle_with<F>(&mut self, mut executor: F) -> usize
    where
        F: FnMut(&str, &[ReconQuery]) -> Vec<IntelFinding>,
    {
        let mut total_new = 0;
        for _ in 0..5 {
            let prompt = self.build_prompt();
            let queries = self.process_llm_response(&prompt);
            let results = executor(&self.config.target, &queries);
            total_new += self.ingest_findings(results);
            self.advance_phase();
        }
        total_new
    }

    /// Generate the final intelligence report.
    pub fn generate_report(&self) -> IntelReport {
        let mut source_counts: HashMap<String, usize> = HashMap::new();
        let mut type_counts: HashMap<String, usize> = HashMap::new();
        for f in &self.findings {
            *source_counts.entry(f.source.to_string()).or_default() += 1;
            *type_counts.entry(f.finding_type.to_string()).or_default() += 1;
        }
        IntelReport {
            target: self.config.target.clone(),
            findings: self.findings.clone(),
            total_queries_executed: self.queries_executed,
            iterations_completed: self.iteration,
            convergence_reached: self.has_converged(),
            phase_durations_ms: self.phase_durations_ms.clone(),
            source_counts,
            finding_type_counts: type_counts,
            generated_at_ms: timestamp_ms(),
            confidence_summary: ConfidenceSummary::from_findings(&self.findings),
        }
    }
}

/// Derive follow-up queries from a finding (e.g., found email → search for that email).
pub fn derive_followup_queries(finding: &IntelFinding) -> Vec<ReconQuery> {
    let mut queries = Vec::new();
    match finding.finding_type {
        FindingType::EmailAddress => {
            queries.push(ReconQuery {
                query_text: format!("\"{}\"", finding.value),
                source: IntelSource::WebSearch,
                priority: 0.8,
                rationale: format!("Search for mentions of discovered email {}", finding.value),
                derived_from: Some(finding.id),
            });
            queries.push(ReconQuery {
                query_text: format!("\"{}\"", finding.value),
                source: IntelSource::PasteSite,
                priority: 0.7,
                rationale: "Check paste sites for leaked credentials".to_string(),
                derived_from: Some(finding.id),
            });
            queries.push(ReconQuery {
                query_text: finding.value.clone(),
                source: IntelSource::CodeRepository,
                priority: 0.9,
                rationale: "Search code repos for hardcoded email/credentials".to_string(),
                derived_from: Some(finding.id),
            });
        }
        FindingType::Domain | FindingType::Subdomain => {
            queries.push(ReconQuery {
                query_text: finding.value.clone(),
                source: IntelSource::Dns,
                priority: 0.9,
                rationale: format!("Enumerate DNS records for {}", finding.value),
                derived_from: Some(finding.id),
            });
            queries.push(ReconQuery {
                query_text: finding.value.clone(),
                source: IntelSource::CertificateTransparency,
                priority: 0.85,
                rationale: "Discover certificates and alternative names".to_string(),
                derived_from: Some(finding.id),
            });
            queries.push(ReconQuery {
                query_text: finding.value.clone(),
                source: IntelSource::Whois,
                priority: 0.7,
                rationale: "Discover registrant info and related domains".to_string(),
                derived_from: Some(finding.id),
            });
        }
        FindingType::Username | FindingType::PersonName => {
            queries.push(ReconQuery {
                query_text: format!("\"{}\"", finding.value),
                source: IntelSource::SocialMedia,
                priority: 0.8,
                rationale: format!("Find social profiles for {}", finding.value),
                derived_from: Some(finding.id),
            });
            queries.push(ReconQuery {
                query_text: finding.value.clone(),
                source: IntelSource::CodeRepository,
                priority: 0.75,
                rationale: "Search for code repos and contributions".to_string(),
                derived_from: Some(finding.id),
            });
        }
        FindingType::IpAddress => {
            queries.push(ReconQuery {
                query_text: finding.value.clone(),
                source: IntelSource::WebSearch,
                priority: 0.6,
                rationale: format!("Reverse lookup and reputation for {}", finding.value),
                derived_from: Some(finding.id),
            });
        }
        FindingType::Technology => {
            queries.push(ReconQuery {
                query_text: format!("{} vulnerability CVE", finding.value),
                source: IntelSource::WebSearch,
                priority: 0.85,
                rationale: format!("Find known CVEs for technology {}", finding.value),
                derived_from: Some(finding.id),
            });
        }
        _ => {}
    }
    queries
}

/// Correlate findings to discover relationships (e.g., email domain matches target domain).
pub fn correlate_findings(findings: &[IntelFinding]) -> Vec<(u64, u64, String)> {
    let mut correlations = Vec::new();
    for i in 0..findings.len() {
        for j in (i + 1)..findings.len() {
            if let Some(rel) = find_relationship(&findings[i], &findings[j]) {
                correlations.push((findings[i].id, findings[j].id, rel));
            }
        }
    }
    correlations
}

fn find_relationship(a: &IntelFinding, b: &IntelFinding) -> Option<String> {
    let a_lower = a.value.to_lowercase();
    let b_lower = b.value.to_lowercase();

    if a.finding_type == FindingType::EmailAddress
        && (b.finding_type == FindingType::Domain || b.finding_type == FindingType::Subdomain)
    {
        if let Some(domain) = a_lower.split('@').nth(1) {
            if domain == b_lower || b_lower.ends_with(&format!(".{domain}")) {
                return Some(format!("Email {} belongs to domain {}", a.value, b.value));
            }
        }
    }

    if b.finding_type == FindingType::EmailAddress
        && (a.finding_type == FindingType::Domain || a.finding_type == FindingType::Subdomain)
    {
        if let Some(domain) = b_lower.split('@').nth(1) {
            if domain == a_lower || a_lower.ends_with(&format!(".{domain}")) {
                return Some(format!("Email {} belongs to domain {}", b.value, a.value));
            }
        }
    }

    if a.finding_type == FindingType::Subdomain && b.finding_type == FindingType::Domain {
        if a_lower.ends_with(&format!(".{}", b_lower)) {
            return Some(format!("{} is subdomain of {}", a.value, b.value));
        }
    }
    if b.finding_type == FindingType::Subdomain && a.finding_type == FindingType::Domain {
        if b_lower.ends_with(&format!(".{}", a_lower)) {
            return Some(format!("{} is subdomain of {}", b.value, a.value));
        }
    }

    if a.finding_type == FindingType::IpAddress && b.finding_type == FindingType::IpAddress {
        let a_parts: Vec<&str> = a_lower.split('.').collect();
        let b_parts: Vec<&str> = b_lower.split('.').collect();
        if a_parts.len() == 4
            && b_parts.len() == 4
            && a_parts[..3] == b_parts[..3]
            && a_parts[3] != b_parts[3]
        {
            return Some(format!("{} and {} share same /24 subnet", a.value, b.value));
        }
    }

    None
}

#[cfg(test)]
#[path = "autonomous_recon_test.rs"]
mod tests;
