use serde::{Deserialize, Serialize};
use std::path::PathBuf;
use std::process::{Command, Stdio};
use std::time::Duration;

/// Configuration for launching an opencode session.
///
/// Controls which model to use, where the workspace lives, and timeout limits.
/// The `prompt_file` field points to the mission prompt .md that opencode reads
/// as its system context (P2c). The `briefing` field is the serialized scan
/// state (P2a) appended to the prompt.
#[derive(Debug, Clone)]
pub struct OpenCodeConfig {
    pub binary: String,
    pub workspace_dir: PathBuf,
    pub model: String,
    pub timeout: Duration,
    pub prompt_file: Option<PathBuf>,
    pub format: OutputFormat,
}

impl Default for OpenCodeConfig {
    fn default() -> Self {
        Self {
            binary: "opencode".to_string(),
            workspace_dir: PathBuf::from("."),
            model: "anthropic:claude-sonnet-4-20250514".to_string(),
            timeout: Duration::from_secs(300),
            prompt_file: None,
            format: OutputFormat::Json,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OutputFormat {
    Json,
    Text,
}

impl OutputFormat {
    fn as_flag(&self) -> &'static str {
        match self {
            Self::Json => "json",
            Self::Text => "text",
        }
    }
}

/// A hypothesis generated by the Brain about a potential vulnerability.
///
/// Maps directly to what the LLM outputs: an endpoint, vulnerability class,
/// reasoning trace, suggested payloads, and a confidence estimate.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentHypothesis {
    pub endpoint: String,
    pub vulnerability_class: String,
    pub reasoning: String,
    pub suggested_payloads: Vec<String>,
    pub confidence: f64,
    pub priority: u32,
}

/// A concrete next action the Brain wants AEGIS to perform.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentAction {
    pub action_type: String,
    pub target: String,
    pub parameters: serde_json::Value,
    pub rationale: String,
}

/// The full structured response from an opencode session.
///
/// The Brain returns hypotheses to test, actions to take, and a summary
/// of its reasoning. `raw_output` preserves the complete LLM response
/// for debugging and audit logging.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentResponse {
    pub hypotheses: Vec<AgentHypothesis>,
    pub actions: Vec<AgentAction>,
    pub reasoning_summary: String,
    pub raw_output: String,
    pub tokens_used: Option<u64>,
    pub duration_ms: u64,
}

/// Errors from the opencode bridge.
#[derive(Debug)]
pub enum BridgeError {
    BinaryNotFound(String),
    SpawnFailed(String),
    Timeout,
    ProcessFailed { exit_code: i32, stderr: String },
    ParseFailed(String),
    Io(std::io::Error),
}

impl std::fmt::Display for BridgeError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::BinaryNotFound(bin) => write!(f, "opencode binary not found: {bin}"),
            Self::SpawnFailed(msg) => write!(f, "failed to spawn opencode: {msg}"),
            Self::Timeout => write!(f, "opencode timed out"),
            Self::ProcessFailed { exit_code, stderr } => {
                write!(f, "opencode exited with {exit_code}: {stderr}")
            }
            Self::ParseFailed(msg) => write!(f, "failed to parse opencode output: {msg}"),
            Self::Io(e) => write!(f, "io error: {e}"),
        }
    }
}

impl std::error::Error for BridgeError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Io(e) => Some(e),
            _ => None,
        }
    }
}

impl From<std::io::Error> for BridgeError {
    fn from(e: std::io::Error) -> Self {
        Self::Io(e)
    }
}

/// Check whether the opencode binary is available on PATH.
pub fn is_opencode_available(binary: &str) -> bool {
    Command::new("which")
        .arg(binary)
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

/// Build the full prompt by combining the mission prompt file with the
/// scan briefing. The mission prompt provides the offensive security
/// instructions; the briefing provides the current scan state.
pub fn build_prompt(mission_prompt: Option<&str>, briefing: &str) -> String {
    match mission_prompt {
        Some(mission) => format!("{}\n\n---\n\n{}", mission, briefing),
        None => briefing.to_string(),
    }
}

/// Assemble the command-line arguments for `opencode run`.
pub fn build_command_args(config: &OpenCodeConfig, prompt: &str) -> Vec<String> {
    let args = vec![
        "run".to_string(),
        "--dir".to_string(),
        config.workspace_dir.to_string_lossy().to_string(),
        "--model".to_string(),
        config.model.clone(),
        "--format".to_string(),
        config.format.as_flag().to_string(),
        prompt.to_string(),
    ];
    args
}

/// Spawn an opencode process with the given prompt and capture its output.
///
/// Returns the raw stdout as a string. The caller is responsible for parsing.
/// The process is killed if it exceeds the configured timeout.
pub fn run_opencode(config: &OpenCodeConfig, prompt: &str) -> Result<String, BridgeError> {
    let args = build_command_args(config, prompt);

    let child = Command::new(&config.binary)
        .args(&args)
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|e| {
            if e.kind() == std::io::ErrorKind::NotFound {
                BridgeError::BinaryNotFound(config.binary.clone())
            } else {
                BridgeError::SpawnFailed(e.to_string())
            }
        })?;

    let timeout = config.timeout;
    let start = std::time::Instant::now();

    let result = child.wait_with_output().map_err(BridgeError::Io)?;

    let elapsed = start.elapsed();
    if elapsed > timeout {
        return Err(BridgeError::Timeout);
    }

    if !result.status.success() {
        let stderr = String::from_utf8_lossy(&result.stderr).to_string();
        return Err(BridgeError::ProcessFailed {
            exit_code: result.status.code().unwrap_or(-1),
            stderr,
        });
    }

    Ok(String::from_utf8_lossy(&result.stdout).to_string())
}

/// Parse the raw JSON output from opencode into a structured `AgentResponse`.
///
/// The expected JSON shape from the Brain:
/// ```json
/// {
///   "hypotheses": [...],
///   "actions": [...],
///   "reasoning_summary": "...",
///   "tokens_used": 1234
/// }
/// ```
///
/// If the output isn't valid JSON, attempts to extract a JSON block from
/// markdown code fences. Falls back to treating the entire output as a
/// text-only reasoning summary with no structured data.
pub fn parse_agent_response(raw: &str, duration_ms: u64) -> Result<AgentResponse, BridgeError> {
    if let Ok(mut resp) = serde_json::from_str::<AgentResponse>(raw) {
        resp.raw_output = raw.to_string();
        resp.duration_ms = duration_ms;
        return Ok(resp);
    }

    if let Some(json_block) = extract_json_block(raw) {
        if let Ok(mut resp) = serde_json::from_str::<AgentResponse>(&json_block) {
            resp.raw_output = raw.to_string();
            resp.duration_ms = duration_ms;
            return Ok(resp);
        }

        if let Ok(partial) = serde_json::from_str::<serde_json::Value>(&json_block) {
            return Ok(response_from_partial_json(&partial, raw, duration_ms));
        }
    }

    Ok(AgentResponse {
        hypotheses: Vec::new(),
        actions: Vec::new(),
        reasoning_summary: raw.to_string(),
        raw_output: raw.to_string(),
        tokens_used: None,
        duration_ms,
    })
}

fn extract_json_block(text: &str) -> Option<String> {
    let fence_start = text.find("```json")?;
    let content_start = text[fence_start..].find('\n')? + fence_start + 1;
    let fence_end = text[content_start..].find("```")?;
    Some(
        text[content_start..content_start + fence_end]
            .trim()
            .to_string(),
    )
}

fn response_from_partial_json(
    val: &serde_json::Value,
    raw: &str,
    duration_ms: u64,
) -> AgentResponse {
    let hypotheses: Vec<AgentHypothesis> = val
        .get("hypotheses")
        .and_then(|v| serde_json::from_value(v.clone()).ok())
        .unwrap_or_default();

    let actions: Vec<AgentAction> = val
        .get("actions")
        .and_then(|v| serde_json::from_value(v.clone()).ok())
        .unwrap_or_default();

    let reasoning = val
        .get("reasoning_summary")
        .or_else(|| val.get("reasoning"))
        .or_else(|| val.get("summary"))
        .and_then(|v| v.as_str())
        .unwrap_or("")
        .to_string();

    let tokens = val.get("tokens_used").and_then(|v| v.as_u64());

    AgentResponse {
        hypotheses,
        actions,
        reasoning_summary: reasoning,
        raw_output: raw.to_string(),
        tokens_used: tokens,
        duration_ms,
    }
}

/// Full pipeline: build prompt → spawn opencode → parse response.
///
/// This is the primary entry point for the feedback loop (P2e).
pub fn invoke_brain(
    config: &OpenCodeConfig,
    mission_prompt: Option<&str>,
    briefing: &str,
) -> Result<AgentResponse, BridgeError> {
    let prompt = build_prompt(mission_prompt, briefing);
    let start = std::time::Instant::now();
    let raw = run_opencode(config, &prompt)?;
    let duration_ms = start.elapsed().as_millis() as u64;
    parse_agent_response(&raw, duration_ms)
}

#[cfg(test)]
#[path = "opencode_bridge_test.rs"]
mod opencode_bridge_test;
