use super::waf_fingerprinter_v2::*;
use std::collections::HashMap;

fn response_with_headers(headers: Vec<(&str, &str)>) -> ResponseFingerprint {
    ResponseFingerprint {
        status_code: 403,
        headers: headers
            .into_iter()
            .map(|(k, v)| (k.to_string(), v.to_string()))
            .collect(),
        body_snippet: String::new(),
    }
}

fn response_with_body(body: &str) -> ResponseFingerprint {
    ResponseFingerprint {
        status_code: 403,
        headers: HashMap::new(),
        body_snippet: body.to_string(),
    }
}

#[test]
fn test_vendor_count_at_least_twenty() {
    let fp = WafFingerprinterV2::new();
    assert!(
        fp.vendor_count() >= 20,
        "Expected 20+ vendors, got {}",
        fp.vendor_count()
    );
}

#[test]
fn test_cloudflare_detection_by_cf_ray() {
    let fp = WafFingerprinterV2::new();
    let resp = response_with_headers(vec![("cf-ray", "7f1234567890abcd-SJC")]);
    let result = fp.fingerprint(&resp);
    assert_eq!(result.primary_vendor, WafVendor::Cloudflare);
    assert!(result.confidence > 0.5);
}

#[test]
fn test_cloudflare_detection_by_server_header() {
    let fp = WafFingerprinterV2::new();
    let resp = response_with_headers(vec![("server", "cloudflare")]);
    let result = fp.fingerprint(&resp);
    assert_eq!(result.primary_vendor, WafVendor::Cloudflare);
}

#[test]
fn test_akamai_detection() {
    let fp = WafFingerprinterV2::new();
    let resp = response_with_headers(vec![("server", "AkamaiGHost")]);
    let result = fp.fingerprint(&resp);
    assert_eq!(result.primary_vendor, WafVendor::Akamai);
    assert!(result.confidence > 0.5);
}

#[test]
fn test_aws_waf_detection() {
    let fp = WafFingerprinterV2::new();
    let resp = response_with_headers(vec![
        ("x-amzn-requestid", "abc123"),
        ("x-amzn-waf-action", "BLOCK"),
    ]);
    let result = fp.fingerprint(&resp);
    assert_eq!(result.primary_vendor, WafVendor::AwsWaf);
}

#[test]
fn test_modsecurity_detection() {
    let fp = WafFingerprinterV2::new();
    let resp = ResponseFingerprint {
        status_code: 403,
        headers: vec![("server".to_string(), "Apache/2.4 mod_security".to_string())]
            .into_iter()
            .collect(),
        body_snippet: "This error was generated by Mod_Security".to_string(),
    };
    let result = fp.fingerprint(&resp);
    assert_eq!(result.primary_vendor, WafVendor::ModSecurity);
}

#[test]
fn test_imperva_detection_by_header() {
    let fp = WafFingerprinterV2::new();
    let resp = response_with_headers(vec![("x-iinfo", "1-2-3")]);
    let result = fp.fingerprint(&resp);
    assert_eq!(result.primary_vendor, WafVendor::Imperva);
}

#[test]
fn test_imperva_detection_by_body() {
    let fp = WafFingerprinterV2::new();
    let resp = response_with_body("Incapsula incident ID: 123456789");
    let result = fp.fingerprint(&resp);
    assert_eq!(result.primary_vendor, WafVendor::Imperva);
}

#[test]
fn test_f5_bigip_detection() {
    let fp = WafFingerprinterV2::new();
    let resp = response_with_headers(vec![("server", "BIG-IP")]);
    let result = fp.fingerprint(&resp);
    assert_eq!(result.primary_vendor, WafVendor::F5BigIp);
}

#[test]
fn test_barracuda_detection() {
    let fp = WafFingerprinterV2::new();
    let resp = response_with_headers(vec![("server", "Barracuda/4.0")]);
    let result = fp.fingerprint(&resp);
    assert_eq!(result.primary_vendor, WafVendor::Barracuda);
}

#[test]
fn test_sucuri_detection() {
    let fp = WafFingerprinterV2::new();
    let resp = response_with_headers(vec![("x-sucuri-id", "abc123")]);
    let result = fp.fingerprint(&resp);
    assert_eq!(result.primary_vendor, WafVendor::Sucuri);
}

#[test]
fn test_wordfence_detection_by_body() {
    let fp = WafFingerprinterV2::new();
    let resp = response_with_body("Generated by Wordfence at Thu, 01 Jan 2024");
    let result = fp.fingerprint(&resp);
    assert_eq!(result.primary_vendor, WafVendor::Wordfence);
}

#[test]
fn test_azure_front_door_detection() {
    let fp = WafFingerprinterV2::new();
    let resp = response_with_headers(vec![("x-azure-ref", "ref123abc")]);
    let result = fp.fingerprint(&resp);
    assert_eq!(result.primary_vendor, WafVendor::AzureFrontDoor);
}

#[test]
fn test_fastly_detection() {
    let fp = WafFingerprinterV2::new();
    let resp = response_with_headers(vec![("x-fastly-request-id", "abc123")]);
    let result = fp.fingerprint(&resp);
    assert_eq!(result.primary_vendor, WafVendor::Fastly);
}

#[test]
fn test_stackpath_detection() {
    let fp = WafFingerprinterV2::new();
    let resp = response_with_headers(vec![("x-sp-waf", "1")]);
    let result = fp.fingerprint(&resp);
    assert_eq!(result.primary_vendor, WafVendor::StackPath);
}

#[test]
fn test_fortiweb_detection() {
    let fp = WafFingerprinterV2::new();
    let resp = response_with_headers(vec![("server", "FortiWeb/5.0")]);
    let result = fp.fingerprint(&resp);
    assert_eq!(result.primary_vendor, WafVendor::FortiWeb);
}

#[test]
fn test_reblaze_detection() {
    let fp = WafFingerprinterV2::new();
    let resp = response_with_headers(vec![("rbzid", "session123")]);
    let result = fp.fingerprint(&resp);
    assert_eq!(result.primary_vendor, WafVendor::Reblaze);
}

#[test]
fn test_safedog_detection() {
    let fp = WafFingerprinterV2::new();
    let resp = response_with_headers(vec![("waf-dog", "1")]);
    let result = fp.fingerprint(&resp);
    assert_eq!(result.primary_vendor, WafVendor::SafeDog);
}

#[test]
fn test_wallarm_detection() {
    let fp = WafFingerprinterV2::new();
    let resp = response_with_headers(vec![("server", "nginx/wallarm")]);
    let result = fp.fingerprint(&resp);
    assert_eq!(result.primary_vendor, WafVendor::WallArm);
}

#[test]
fn test_unknown_when_no_match() {
    let fp = WafFingerprinterV2::new();
    let resp = response_with_headers(vec![("server", "nginx/1.24")]);
    let result = fp.fingerprint(&resp);
    assert_eq!(result.primary_vendor, WafVendor::Unknown);
    assert!(result.detected_vendors.is_empty());
}

#[test]
fn test_bypass_strategy_returned() {
    let fp = WafFingerprinterV2::new();
    let resp = response_with_headers(vec![("cf-ray", "abc123-SJC")]);
    let result = fp.fingerprint(&resp);
    assert!(!result.bypass_strategies.is_empty());
    assert_eq!(result.bypass_strategies[0].vendor, WafVendor::Cloudflare);
}

#[test]
fn test_multi_response_fingerprinting() {
    let fp = WafFingerprinterV2::new();
    let responses = vec![
        response_with_headers(vec![("cf-ray", "abc123")]),
        response_with_headers(vec![("server", "cloudflare")]),
        response_with_body("Attention Required! | Cloudflare"),
    ];
    let result = fp.fingerprint_multi(&responses);
    assert_eq!(result.primary_vendor, WafVendor::Cloudflare);
    assert!(result.confidence > 0.5);
}

#[test]
fn test_get_bypass_strategy() {
    let fp = WafFingerprinterV2::new();
    let strat = fp.get_bypass_strategy(WafVendor::Cloudflare);
    assert!(strat.is_some());
    let strat = strat.unwrap();
    assert!(!strat.preferred_encodings.is_empty());
    assert!(strat.timing_advice_ms.0 < strat.timing_advice_ms.1);
}

#[test]
fn test_evidence_populated() {
    let fp = WafFingerprinterV2::new();
    let resp = response_with_headers(vec![("cf-ray", "abc"), ("server", "cloudflare")]);
    let result = fp.fingerprint(&resp);
    assert!(result.evidence.len() >= 2);
}

#[test]
fn test_display_for_all_vendors() {
    let vendors = vec![
        WafVendor::Cloudflare,
        WafVendor::Akamai,
        WafVendor::AwsWaf,
        WafVendor::ModSecurity,
        WafVendor::Imperva,
        WafVendor::F5BigIp,
        WafVendor::Barracuda,
        WafVendor::Sucuri,
        WafVendor::Wordfence,
        WafVendor::AzureFrontDoor,
        WafVendor::Fastly,
        WafVendor::StackPath,
        WafVendor::DenyAll,
        WafVendor::FortiWeb,
        WafVendor::Radware,
        WafVendor::SonicWall,
        WafVendor::Citrix,
        WafVendor::Palo,
        WafVendor::Reblaze,
        WafVendor::SafeDog,
        WafVendor::Comodo,
        WafVendor::WallArm,
        WafVendor::Unknown,
    ];
    for v in vendors {
        let s = format!("{}", v);
        assert!(!s.is_empty());
    }
}

#[test]
fn test_case_insensitive_header_matching() {
    let fp = WafFingerprinterV2::new();
    let resp = response_with_headers(vec![("CF-RAY", "abc123-SJC")]);
    let result = fp.fingerprint(&resp);
    assert_eq!(result.primary_vendor, WafVendor::Cloudflare);
}

#[test]
fn test_multiple_waf_detection() {
    let fp = WafFingerprinterV2::new();
    let resp = response_with_headers(vec![("cf-ray", "abc123"), ("x-sucuri-id", "xyz789")]);
    let result = fp.fingerprint(&resp);
    assert!(result.detected_vendors.len() >= 2);
}
