[package]
name = "aegis-reporting"
version.workspace = true
edition.workspace = true

[dependencies]
aegis-protocol = { path = "../protocol" }
aegis-knowledge-graph = { path = "../knowledge-graph" }
serde = { workspace = true }
serde_json = { workspace = true }
ciborium = { workspace = true }
sha3 = { workspace = true }
uuid = { workspace = true }
sarif_rust = { workspace = true }
aegis-fuzzing = { path = "../fuzzing" }
