use aegis_protocol::finding::VulnerabilityClass;

use crate::report_format::{DefenseSummary, ReportMetadata};
use crate::sarif_emitter::{SarifFinding, attack_technique_for, cwe_for, remediation_for};

/// Configuration for the standalone HTML report generator.
pub struct HtmlReportConfig {
    pub title: String,
    pub tool_version: String,
    pub include_attack_chain: bool,
    pub include_remediation: bool,
}

impl Default for HtmlReportConfig {
    fn default() -> Self {
        Self {
            title: "AEGIS Security Scan Report".to_string(),
            tool_version: "0.1.0".to_string(),
            include_attack_chain: true,
            include_remediation: true,
        }
    }
}

/// Severity rating string from composite score.
///
/// Thresholds mirror `report_format::severity_rating`:
/// - `>=70` → Critical
/// - `>=40` → High
/// - `>=20` → Medium
/// - else   → Low
pub fn severity_rating(score: f64) -> &'static str {
    if score >= 70.0 {
        "Critical"
    } else if score >= 40.0 {
        "High"
    } else if score >= 20.0 {
        "Medium"
    } else {
        "Low"
    }
}

/// Map a severity rating label to a hex colour.
pub fn severity_color(rating: &str) -> &'static str {
    match rating {
        "Critical" => "#ff4444",
        "High" => "#ff8c00",
        "Medium" => "#ffd700",
        "Low" => "#44ff44",
        _ => "#888888",
    }
}

/// Escape the five characters that are meaningful in HTML.
pub fn html_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#x27;"),
            _ => out.push(ch),
        }
    }
    out
}

/// Produce a complete, self-contained HTML document for the scan results.
pub fn generate_html_report(
    findings: &[SarifFinding],
    config: &HtmlReportConfig,
    metadata: Option<&ReportMetadata>,
    defense_summary: Option<&DefenseSummary>,
) -> String {
    let css = generate_css();
    let executive_summary = generate_executive_summary(findings, metadata, defense_summary);
    let finding_cards = generate_finding_cards(findings, config.include_remediation);
    let findings_table = generate_findings_table(findings);
    let attack_chain_section = if config.include_attack_chain {
        generate_attack_chain_svg(findings)
    } else {
        String::new()
    };
    let js = generate_js();

    let escaped_title = html_escape(&config.title);

    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{escaped_title}</title>
<style>
{css}
</style>
</head>
<body>
<header>
<h1>{escaped_title}</h1>
<p class="tool-version">Generated by AEGIS v{version}</p>
</header>
<main>
{executive_summary}
{attack_chain_section}
<section id="findings-table-section">
<h2>Findings Table</h2>
{findings_table}
</section>
<section id="finding-cards-section">
<h2>Finding Details</h2>
{finding_cards}
</section>
</main>
<footer>
<p>Report generated by AEGIS Security Scanner v{version}</p>
</footer>
<script>
{js}
</script>
</body>
</html>"#,
        escaped_title = escaped_title,
        version = html_escape(&config.tool_version),
        css = css,
        executive_summary = executive_summary,
        attack_chain_section = attack_chain_section,
        finding_cards = finding_cards,
        findings_table = findings_table,
        js = js,
    )
}

fn generate_css() -> String {
    r#"
:root {
    --bg-primary: #1a1a2e;
    --bg-secondary: #16213e;
    --bg-card: #0f3460;
    --text-primary: #e0e0e0;
    --text-secondary: #a0a0b0;
    --border-color: #2a2a4a;
    --accent: #00b4d8;
    --critical: #ff4444;
    --high: #ff8c00;
    --medium: #ffd700;
    --low: #44ff44;
}

* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    background: var(--bg-primary);
    color: var(--text-primary);
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    line-height: 1.6;
    padding: 2rem;
}

header {
    text-align: center;
    padding: 2rem 0;
    border-bottom: 2px solid var(--border-color);
    margin-bottom: 2rem;
}

header h1 {
    font-size: 2rem;
    color: var(--accent);
}

.tool-version {
    color: var(--text-secondary);
    font-size: 0.9rem;
    margin-top: 0.5rem;
}

main {
    max-width: 1200px;
    margin: 0 auto;
}

section {
    margin-bottom: 2.5rem;
}

h2 {
    color: var(--accent);
    border-bottom: 1px solid var(--border-color);
    padding-bottom: 0.5rem;
    margin-bottom: 1rem;
    font-size: 1.4rem;
}

h3 {
    color: var(--text-primary);
    margin-bottom: 0.5rem;
    font-size: 1.1rem;
}

.summary-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    gap: 1rem;
    margin-bottom: 1.5rem;
}

.summary-card {
    background: var(--bg-secondary);
    border: 1px solid var(--border-color);
    border-radius: 8px;
    padding: 1.2rem;
    text-align: center;
}

.summary-card .count {
    font-size: 2.2rem;
    font-weight: bold;
}

.summary-card .label {
    color: var(--text-secondary);
    font-size: 0.85rem;
    text-transform: uppercase;
    letter-spacing: 0.05em;
}

.badge {
    display: inline-block;
    padding: 0.15rem 0.6rem;
    border-radius: 4px;
    font-size: 0.75rem;
    font-weight: 700;
    text-transform: uppercase;
    color: #111;
}

.badge-critical { background: var(--critical); }
.badge-high     { background: var(--high); }
.badge-medium   { background: var(--medium); }
.badge-low      { background: var(--low); }

.finding-card {
    background: var(--bg-secondary);
    border: 1px solid var(--border-color);
    border-radius: 8px;
    margin-bottom: 1rem;
    overflow: hidden;
}

.finding-card-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 0.8rem 1.2rem;
    cursor: pointer;
    background: var(--bg-card);
    user-select: none;
}

.finding-card-header:hover {
    opacity: 0.9;
}

.finding-card-header .rule-id {
    font-weight: 600;
    color: var(--accent);
}

.finding-card-body {
    padding: 1.2rem;
    display: none;
}

.finding-card.open .finding-card-body {
    display: block;
}

.finding-detail {
    margin-bottom: 0.6rem;
}

.finding-detail .detail-label {
    color: var(--text-secondary);
    font-size: 0.8rem;
    text-transform: uppercase;
    letter-spacing: 0.04em;
}

.finding-detail .detail-value {
    margin-top: 0.15rem;
}

.remediation-box {
    background: rgba(0, 180, 216, 0.1);
    border-left: 3px solid var(--accent);
    padding: 0.8rem 1rem;
    margin-top: 0.8rem;
    border-radius: 0 4px 4px 0;
}

table.findings-table {
    width: 100%;
    border-collapse: collapse;
    font-size: 0.9rem;
}

table.findings-table th,
table.findings-table td {
    padding: 0.6rem 0.8rem;
    border: 1px solid var(--border-color);
    text-align: left;
}

table.findings-table th {
    background: var(--bg-card);
    color: var(--accent);
    cursor: pointer;
    user-select: none;
    white-space: nowrap;
}

table.findings-table th:hover {
    opacity: 0.85;
}

table.findings-table tr:nth-child(even) {
    background: var(--bg-secondary);
}

table.findings-table tr:hover {
    background: rgba(0, 180, 216, 0.08);
}

.filter-bar {
    margin-bottom: 1rem;
    display: flex;
    gap: 0.8rem;
    flex-wrap: wrap;
    align-items: center;
}

.filter-bar input,
.filter-bar select {
    background: var(--bg-secondary);
    color: var(--text-primary);
    border: 1px solid var(--border-color);
    padding: 0.4rem 0.6rem;
    border-radius: 4px;
    font-size: 0.85rem;
}

.attack-chain-svg {
    overflow-x: auto;
    margin-bottom: 1rem;
}

.defense-info {
    background: var(--bg-secondary);
    border: 1px solid var(--border-color);
    border-radius: 8px;
    padding: 1rem;
    margin-top: 1rem;
}

.defense-info .defense-item {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    margin-bottom: 0.4rem;
}

.defense-info .indicator {
    width: 10px;
    height: 10px;
    border-radius: 50%;
    display: inline-block;
}

.indicator-active   { background: var(--low); }
.indicator-inactive { background: var(--critical); }

footer {
    text-align: center;
    padding: 2rem 0;
    border-top: 1px solid var(--border-color);
    color: var(--text-secondary);
    font-size: 0.8rem;
}
"#
    .to_string()
}

fn generate_js() -> String {
    r#"
(function() {
    /* Collapsible finding cards */
    document.querySelectorAll('.finding-card-header').forEach(function(header) {
        header.addEventListener('click', function() {
            header.parentElement.classList.toggle('open');
        });
    });

    /* Sortable table columns */
    document.querySelectorAll('table.findings-table th[data-sort]').forEach(function(th) {
        th.addEventListener('click', function() {
            var table = th.closest('table');
            var tbody = table.querySelector('tbody');
            var rows = Array.from(tbody.querySelectorAll('tr'));
            var colIndex = parseInt(th.getAttribute('data-sort'), 10);
            var isNumeric = th.hasAttribute('data-numeric');
            var ascending = th.getAttribute('data-dir') !== 'asc';
            th.setAttribute('data-dir', ascending ? 'asc' : 'desc');

            rows.sort(function(a, b) {
                var aText = a.cells[colIndex].textContent.trim();
                var bText = b.cells[colIndex].textContent.trim();
                if (isNumeric) {
                    return ascending
                        ? parseFloat(aText) - parseFloat(bText)
                        : parseFloat(bText) - parseFloat(aText);
                }
                return ascending
                    ? aText.localeCompare(bText)
                    : bText.localeCompare(aText);
            });

            rows.forEach(function(row) { tbody.appendChild(row); });
        });
    });

    /* Filter bar */
    var filterInput = document.getElementById('finding-filter');
    var severitySelect = document.getElementById('severity-filter');

    function applyFilters() {
        var text = (filterInput ? filterInput.value : '').toLowerCase();
        var severity = severitySelect ? severitySelect.value : '';
        var tbody = document.querySelector('table.findings-table tbody');
        if (!tbody) return;
        Array.from(tbody.querySelectorAll('tr')).forEach(function(row) {
            var rowText = row.textContent.toLowerCase();
            var rowSeverity = row.getAttribute('data-severity') || '';
            var matchText = text === '' || rowText.indexOf(text) !== -1;
            var matchSeverity = severity === '' || rowSeverity === severity;
            row.style.display = (matchText && matchSeverity) ? '' : 'none';
        });
    }

    if (filterInput) filterInput.addEventListener('input', applyFilters);
    if (severitySelect) severitySelect.addEventListener('change', applyFilters);
})();
"#
    .to_string()
}

fn generate_executive_summary(
    findings: &[SarifFinding],
    metadata: Option<&ReportMetadata>,
    defense_summary: Option<&DefenseSummary>,
) -> String {
    let mut critical = 0usize;
    let mut high = 0usize;
    let mut medium = 0usize;
    let mut low = 0usize;

    for f in findings {
        match severity_rating(f.composite_score) {
            "Critical" => critical += 1,
            "High" => high += 1,
            "Medium" => medium += 1,
            _ => low += 1,
        }
    }

    let total = findings.len();
    let max_composite = findings
        .iter()
        .map(|f| f.composite_score)
        .fold(0.0_f64, f64::max);
    let overall_rating = severity_rating(max_composite);
    let overall_color = severity_color(overall_rating);

    let meta_section = metadata
        .map(|m| {
            format!(
                r#"<div class="summary-card">
    <div class="count" style="font-size:1rem;">{target}</div>
    <div class="label">Target</div>
</div>
<div class="summary-card">
    <div class="count">{duration:.1}s</div>
    <div class="label">Scan Duration</div>
</div>
<div class="summary-card">
    <div class="count">{phases}</div>
    <div class="label">Phases Completed</div>
</div>"#,
                target = html_escape(&m.target_url),
                duration = m.total_duration_secs,
                phases = m.phases_completed,
            )
        })
        .unwrap_or_default();

    let defense_section = defense_summary
        .map(|ds| {
            let waf_indicator = if ds.has_waf {
                "indicator-active"
            } else {
                "indicator-inactive"
            };
            let rl_indicator = if ds.has_rate_limiting {
                "indicator-active"
            } else {
                "indicator-inactive"
            };
            let bd_indicator = if ds.has_bot_detection {
                "indicator-active"
            } else {
                "indicator-inactive"
            };
            let waf_label = ds
                .waf_vendor
                .as_ref()
                .map(|v| format!("WAF ({})", html_escape(v)))
                .unwrap_or_else(|| "WAF".to_string());

            format!(
                r#"<div class="defense-info">
<h3>Defense Posture</h3>
<div class="defense-item"><span class="indicator {waf_indicator}"></span> {waf_label}</div>
<div class="defense-item"><span class="indicator {rl_indicator}"></span> Rate Limiting</div>
<div class="defense-item"><span class="indicator {bd_indicator}"></span> Bot Detection</div>
</div>"#,
                waf_indicator = waf_indicator,
                waf_label = waf_label,
                rl_indicator = rl_indicator,
                bd_indicator = bd_indicator,
            )
        })
        .unwrap_or_default();

    format!(
        r#"<section id="executive-summary">
<h2>Executive Summary</h2>
<div class="summary-grid">
<div class="summary-card">
    <div class="count">{total}</div>
    <div class="label">Total Findings</div>
</div>
<div class="summary-card">
    <div class="count" style="color:{critical_color};">{critical}</div>
    <div class="label">Critical</div>
</div>
<div class="summary-card">
    <div class="count" style="color:{high_color};">{high}</div>
    <div class="label">High</div>
</div>
<div class="summary-card">
    <div class="count" style="color:{medium_color};">{medium}</div>
    <div class="label">Medium</div>
</div>
<div class="summary-card">
    <div class="count" style="color:{low_color};">{low}</div>
    <div class="label">Low</div>
</div>
<div class="summary-card">
    <div class="count" style="color:{overall_color};">{overall_rating}</div>
    <div class="label">Overall Risk</div>
</div>
{meta_section}
</div>
{defense_section}
</section>"#,
        total = total,
        critical = critical,
        critical_color = severity_color("Critical"),
        high = high,
        high_color = severity_color("High"),
        medium = medium,
        medium_color = severity_color("Medium"),
        low = low,
        low_color = severity_color("Low"),
        overall_rating = overall_rating,
        overall_color = overall_color,
        meta_section = meta_section,
        defense_section = defense_section,
    )
}

fn generate_finding_cards(findings: &[SarifFinding], include_remediation: bool) -> String {
    if findings.is_empty() {
        return "<p>No findings to display.</p>".to_string();
    }

    let mut cards = String::new();
    for (idx, f) in findings.iter().enumerate() {
        let rating = severity_rating(f.composite_score);
        let badge_class = match rating {
            "Critical" => "badge-critical",
            "High" => "badge-high",
            "Medium" => "badge-medium",
            _ => "badge-low",
        };
        let cwe_text = f
            .vulnerability_class
            .as_ref()
            .map(|vc| cwe_for(vc).to_string())
            .unwrap_or_default();
        let attack_text = f
            .vulnerability_class
            .as_ref()
            .map(|vc| attack_technique_for(vc).to_string())
            .unwrap_or_default();
        let remediation_html = if include_remediation {
            f.vulnerability_class
                .as_ref()
                .map(|vc| {
                    format!(
                        r#"<div class="remediation-box">
<div class="detail-label">Remediation</div>
<div class="detail-value">{}</div>
</div>"#,
                        html_escape(remediation_for(vc)),
                    )
                })
                .unwrap_or_default()
        } else {
            String::new()
        };

        let endpoint_html = f
            .endpoint
            .as_ref()
            .map(|ep| {
                format!(
                    r#"<div class="finding-detail">
<span class="detail-label">Endpoint:</span>
<span class="detail-value">{method} {ep}</span>
</div>"#,
                    method = html_escape(f.http_method.as_deref().unwrap_or("GET")),
                    ep = html_escape(ep),
                )
            })
            .unwrap_or_default();

        let parameter_html = f
            .parameter_name
            .as_ref()
            .map(|p| {
                format!(
                    r#"<div class="finding-detail">
<span class="detail-label">Parameter:</span>
<span class="detail-value">{}</span>
</div>"#,
                    html_escape(p),
                )
            })
            .unwrap_or_default();

        let evidence_html = f
            .evidence_level
            .as_ref()
            .map(|e| {
                format!(
                    r#"<div class="finding-detail">
<span class="detail-label">Evidence Level:</span>
<span class="detail-value">{}</span>
</div>"#,
                    html_escape(e),
                )
            })
            .unwrap_or_default();

        let cve_html = f
            .cve_id
            .as_ref()
            .map(|cve| {
                format!(
                    r#"<div class="finding-detail">
<span class="detail-label">CVE:</span>
<span class="detail-value"><a href="https://nvd.nist.gov/vuln/detail/{cve}" style="color:var(--accent);">{cve}</a></span>
</div>"#,
                    cve = html_escape(cve),
                )
            })
            .unwrap_or_default();

        let vuln_class_html = f
            .vulnerability_class
            .as_ref()
            .map(|vc| {
                format!(
                    r#"<div class="finding-detail">
<span class="detail-label">Vulnerability Class:</span>
<span class="detail-value">{}</span>
</div>"#,
                    html_escape(&format!("{vc}")),
                )
            })
            .unwrap_or_default();

        let defense_html = f
            .defense_context
            .as_ref()
            .map(|dc| {
                let mut parts = Vec::new();
                if !dc.defenses_detected.is_empty() {
                    parts.push(format!(
                        "Defenses detected: {}",
                        dc.defenses_detected
                            .iter()
                            .map(|d| html_escape(d))
                            .collect::<Vec<_>>()
                            .join(", ")
                    ));
                }
                if dc.exploitable_despite_waf {
                    parts.push("Exploitable despite WAF".to_string());
                }
                if let Some(tech) = &dc.evasion_technique {
                    parts.push(format!("Evasion: {}", html_escape(tech)));
                }
                if parts.is_empty() {
                    String::new()
                } else {
                    format!(
                        r#"<div class="finding-detail">
<span class="detail-label">Defense Context:</span>
<span class="detail-value">{}</span>
</div>"#,
                        parts.join(" | "),
                    )
                }
            })
            .unwrap_or_default();

        cards.push_str(&format!(
            r#"<div class="finding-card" id="finding-{idx}">
<div class="finding-card-header">
    <span>
        <span class="rule-id">{rule_id}</span>
        — {message_short}
    </span>
    <span class="badge {badge_class}">{rating}</span>
</div>
<div class="finding-card-body">
    <div class="finding-detail">
        <span class="detail-label">Message:</span>
        <span class="detail-value">{message}</span>
    </div>
    <div class="finding-detail">
        <span class="detail-label">Severity / Confidence / Composite:</span>
        <span class="detail-value">{severity:.1} / {confidence:.1} / {composite:.1}</span>
    </div>
    <div class="finding-detail">
        <span class="detail-label">Level:</span>
        <span class="detail-value">{level}</span>
    </div>
    {vuln_class_html}
    {endpoint_html}
    {parameter_html}
    {evidence_html}
    {cve_html}
    {cwe_line}
    {attack_line}
    {defense_html}
    {remediation_html}
</div>
</div>
"#,
            idx = idx,
            rule_id = html_escape(&f.rule_id),
            message_short = html_escape(&truncate_message(&f.message, 80)),
            badge_class = badge_class,
            rating = rating,
            message = html_escape(&f.message),
            severity = f.severity,
            confidence = f.confidence,
            composite = f.composite_score,
            level = f.level.as_str(),
            vuln_class_html = vuln_class_html,
            endpoint_html = endpoint_html,
            parameter_html = parameter_html,
            evidence_html = evidence_html,
            cve_html = cve_html,
            cwe_line = if cwe_text.is_empty() {
                String::new()
            } else {
                format!(
                    r#"<div class="finding-detail"><span class="detail-label">CWE:</span> <span class="detail-value">{cwe_text}</span></div>"#,
                    cwe_text = html_escape(&cwe_text),
                )
            },
            attack_line = if attack_text.is_empty() {
                String::new()
            } else {
                format!(
                    r#"<div class="finding-detail"><span class="detail-label">ATT&amp;CK:</span> <span class="detail-value">{attack_text}</span></div>"#,
                    attack_text = html_escape(&attack_text),
                )
            },
            defense_html = defense_html,
            remediation_html = remediation_html,
        ));
    }

    cards
}

fn truncate_message(msg: &str, max_len: usize) -> String {
    if msg.len() <= max_len {
        msg.to_string()
    } else {
        let mut end = max_len;
        while end > 0 && !msg.is_char_boundary(end) {
            end -= 1;
        }
        format!("{}…", &msg[..end])
    }
}

fn generate_findings_table(findings: &[SarifFinding]) -> String {
    if findings.is_empty() {
        return "<p>No findings to display.</p>".to_string();
    }

    let mut html = String::new();

    html.push_str(
        r#"<div class="filter-bar">
<input id="finding-filter" type="text" placeholder="Filter findings…">
<select id="severity-filter">
    <option value="">All Severities</option>
    <option value="Critical">Critical</option>
    <option value="High">High</option>
    <option value="Medium">Medium</option>
    <option value="Low">Low</option>
</select>
</div>
"#,
    );

    html.push_str(
        r#"<table class="findings-table">
<thead>
<tr>
<th data-sort="0">Rule ID</th>
<th data-sort="1">Severity</th>
<th data-sort="2" data-numeric>Composite</th>
<th data-sort="3">Vulnerability Class</th>
<th data-sort="4">Endpoint</th>
<th data-sort="5">Level</th>
</tr>
</thead>
<tbody>
"#,
    );

    for f in findings {
        let rating = severity_rating(f.composite_score);
        let badge_class = match rating {
            "Critical" => "badge-critical",
            "High" => "badge-high",
            "Medium" => "badge-medium",
            _ => "badge-low",
        };
        let vc_display = f
            .vulnerability_class
            .as_ref()
            .map(|vc| format!("{vc}"))
            .unwrap_or_else(|| "—".to_string());
        let endpoint_display = f.endpoint.as_deref().unwrap_or("—");

        html.push_str(&format!(
            r#"<tr data-severity="{rating}">
<td>{rule_id}</td>
<td><span class="badge {badge_class}">{rating}</span></td>
<td>{composite:.1}</td>
<td>{vc}</td>
<td>{endpoint}</td>
<td>{level}</td>
</tr>
"#,
            rating = rating,
            rule_id = html_escape(&f.rule_id),
            badge_class = badge_class,
            composite = f.composite_score,
            vc = html_escape(&vc_display),
            endpoint = html_escape(endpoint_display),
            level = f.level.as_str(),
        ));
    }

    html.push_str("</tbody>\n</table>");
    html
}

fn generate_attack_chain_svg(findings: &[SarifFinding]) -> String {
    let vuln_classes: Vec<&VulnerabilityClass> = findings
        .iter()
        .filter_map(|f| f.vulnerability_class.as_ref())
        .collect();

    if vuln_classes.is_empty() {
        return String::new();
    }

    // Deduplicate while preserving order.
    let mut seen = std::collections::HashSet::new();
    let unique: Vec<&&VulnerabilityClass> = vuln_classes
        .iter()
        .filter(|vc| seen.insert(format!("{}", vc)))
        .collect();

    let node_width = 180u32;
    let node_height = 44u32;
    let h_gap = 40u32;
    let v_padding = 20u32;
    let node_count = unique.len() as u32;
    let svg_width = node_count * node_width + (node_count.saturating_sub(1)) * h_gap + 40;
    let svg_height = node_height + v_padding * 2;

    let accent = "#00b4d8";
    let text_fill = "#111";

    let mut svg = String::new();
    svg.push_str("<section id=\"attack-chain-section\">\n<h2>Attack Chain</h2>\n<div class=\"attack-chain-svg\">\n");
    svg.push_str(&format!(
        "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"{svg_width}\" height=\"{svg_height}\" viewBox=\"0 0 {svg_width} {svg_height}\">\n",
        svg_width = svg_width,
        svg_height = svg_height,
    ));
    svg.push_str("<defs>\n");
    svg.push_str(&format!(
        "    <marker id=\"arrowhead\" markerWidth=\"10\" markerHeight=\"7\" refX=\"10\" refY=\"3.5\" orient=\"auto\">\n        <polygon points=\"0 0, 10 3.5, 0 7\" fill=\"{accent}\"/>\n    </marker>\n",
        accent = accent,
    ));
    svg.push_str("</defs>\n");

    for (i, vc) in unique.iter().enumerate() {
        let x = 20 + i as u32 * (node_width + h_gap);
        let y = v_padding;
        let label = format!("{}", vc);
        let rating = findings
            .iter()
            .find(|f| {
                f.vulnerability_class
                    .as_ref()
                    .map(|c| format!("{c}") == label)
                    .unwrap_or(false)
            })
            .map(|f| severity_rating(f.composite_score))
            .unwrap_or("Low");
        let fill = severity_color(rating);
        let tx = x + node_width / 2;
        let ty = y + node_height / 2 + 4;
        let escaped_label = html_escape(&truncate_message(&label, 22));

        svg.push_str(&format!(
            "<rect x=\"{x}\" y=\"{y}\" width=\"{nw}\" height=\"{nh}\" rx=\"6\" fill=\"{fill}\" opacity=\"0.85\"/>\n",
            x = x,
            y = y,
            nw = node_width,
            nh = node_height,
            fill = fill,
        ));
        svg.push_str(&format!(
            "<text x=\"{tx}\" y=\"{ty}\" text-anchor=\"middle\" fill=\"{tf}\" font-size=\"11\" font-family=\"sans-serif\" font-weight=\"bold\">{label}</text>\n",
            tx = tx,
            ty = ty,
            tf = text_fill,
            label = escaped_label,
        ));

        // Draw connector arrow to the next node.
        if (i as u32) < node_count - 1 {
            let arrow_x1 = x + node_width;
            let arrow_x2 = x + node_width + h_gap;
            let arrow_y = y + node_height / 2;
            svg.push_str(&format!(
                "<line x1=\"{x1}\" y1=\"{ay}\" x2=\"{x2}\" y2=\"{ay}\" stroke=\"{accent}\" stroke-width=\"2\" marker-end=\"url(#arrowhead)\"/>\n",
                x1 = arrow_x1,
                ay = arrow_y,
                x2 = arrow_x2,
                accent = accent,
            ));
        }
    }

    svg.push_str("</svg>\n</div>\n</section>");
    svg
}
