[package]
name = "aegis-discovery"
version.workspace = true
edition.workspace = true

[dependencies]
aegis-protocol = { path = "../protocol" }
regex = { workspace = true }
reqwest = { workspace = true, features = ["blocking"] }
url = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
